import type {
  Evidence,
  LedgerCategory,
  LedgerEntry,
  ModuleBreakdown,
  ModuleKind,
  OfficialStat,
  WorkCase,
  AnalyticsData,
} from "@/lib/types";
import { ledgerHash } from "@/lib/hash";
import { MP_ALLOCATION_TOTAL_CR, MP_ALLOCATIONS } from "@/lib/mp-allocations.generated";

export const STATE_NAME = "Telangana";
export const PIA = "MoSPI · MPLADS Wing";
export const FISCAL_YEAR = "2025–26";

export const districts = [
  "All districts",
  "Hyderabad",
  "Rangareddy",
  "Medchal-Malkajgiri",
  "Sangareddy",
  "Mahbubnagar",
];

export const mps = [
  "Shri G. Kishan Reddy",
  "Shri Eatala Rajender",
  "Shri Konda Vishweshwar Reddy",
  "Shri Suresh Kumar Shetkar",
  "Smt. D. K. Aruna",
  "Shri Asaduddin Owaisi",
  "Shri M. Raghunandan Rao",
];

export const proposalCategories = [
  "Community Assets",
  "Rural Roads",
  "Drinking Water",
  "Education",
  "Health & Sanitation",
  "Renewable Energy",
  "Social Infrastructure",
];

export const proposalConstituencies = [
  "Secunderabad",
  "Warangal",
  "Chevella",
  "Zahirabad",
  "Mahabubabad",
  "Hyderabad",
  "Medak",
];

function mod(
  module: ModuleKind,
  subScore: number,
  description: string,
  triggered = false,
  evidence?: Evidence
): ModuleBreakdown {
  return { module, subScore, description, triggered, evidence };
}

/* ------------------------------------------------------------------ */
/* 20 Realistic Cases across 5 Telangana Districts                    */
/* ------------------------------------------------------------------ */

export const CASES: WorkCase[] = [
  /* 1 — Spatial & Title Duplicate Overlap (Hyderabad) */
  {
    id: "MPL-2025-1001",
    title: "Community Knowledge & Study Centre, Ward 14, Amberpet, Hyderabad",
    hindiTitle: "सामुदायिक ज्ञान एवं अध्ययन केंद्र, वार्ड 14, अंबरपेट, हैदराबाद",
    category: "Community Assets",
    state: STATE_NAME,
    district: "Hyderabad",
    constituency: "Secunderabad",
    mpName: "Shri Anant Rao (Demo Constituency)",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 16.5,
    sanctionedDate: "12 Jun 2025",
    status: "hold_active",
    statusSince: "15 Jul 2025",
    overview: "Proposed community knowledge centre overlaps with an existing sanctioned study centre just 160 m away. Text similarity is 98% (recomputed live from both descriptions).",
    mpPlainStatus: "Held automatically because a nearly identical study centre was already sanctioned 160m away.",
    compositeScore: 78,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("duplicate", 99, "Text similarity 98% to ‘Community Knowledge & Study Centre, Ward 16’ 160 m away — suspected duplicate sanction.", true, {
        kind: "duplicate",
        twinTitle: "Community Knowledge & Study Centre, Ward 16, Amberpet, Hyderabad",
        twinId: "MPL-2025-1002",
        distanceMeters: 160,
        textSimilarityPct: 98,
        mapX: 48,
        mapY: 52,
      }),
      mod("cost", 22, "Within normal benchmark cost parameters."),
      mod("compliance", 10, "All statutory guardrails cleared."),
      mod("payment", 8, "Releases track initial progress."),
      mod("predictive", 14, "Low historical stall probability."),
      mod("photo", 0, "Initial stage — no duplicate photo flagged."),
      mod("trend", 40, "Disbursal pacing within district variance."),
    ],
  },

  /* 2 — Twin Work of #1 (Hyderabad) */
  {
    id: "MPL-2025-1002",
    title: "Community Knowledge & Study Centre, Ward 16, Amberpet, Hyderabad",
    hindiTitle: "सामुदायिक ज्ञान एवं अध्ययन केंद्र, वार्ड 16, अंबरपेट",
    category: "Community Assets",
    state: STATE_NAME,
    district: "Hyderabad",
    constituency: "Secunderabad",
    mpName: "Shri G. Kishan Reddy",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 15.0,
    sanctionedDate: "10 Jan 2025",
    status: "released",
    statusSince: "20 May 2025",
    overview: "Original sanctioned study centre at Amberpet (Ward 16) currently in active physical execution.",
    mpPlainStatus: "Work in progress on schedule. 70% physical completion achieved.",
    compositeScore: 14,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 6, "No active duplicate conflicts."),
      mod("cost", 12, "Aligned with district Schedule of Rates."),
      mod("compliance", 10, "Clear public municipal land title."),
      mod("payment", 12, "70% funds released matching 75% physical progress."),
      mod("predictive", 8, "On track for early completion."),
      mod("photo", 5, "Stage photos geotagged and authentic."),
      mod("trend", 15, "Disbursal velocity healthy."),
    ],
  },

  /* 3 — Duplicate Pair 2 (Medchal-Malkajgiri) */
  {
    id: "MPL-2025-1003",
    title: "Construction of CC Road and Storm Drain, Pragathi Nagar, Medchal",
    hindiTitle: "सीसी सड़क एवं नाली निर्माण, प्रगति नगर, मेडचल",
    category: "Rural Roads",
    state: STATE_NAME,
    district: "Medchal-Malkajgiri",
    constituency: "Malkajgiri",
    mpName: "Shri Vikram Rathore (Demo Constituency)",
    dmName: "DM Iyer (Demo)",
    sanctionedAmountLakh: 24.0,
    sanctionedDate: "04 Jul 2025",
    status: "hold_active",
    statusSince: "18 Aug 2025",
    overview: "Identical CC Road and storm drain sanctioned 210m from an active municipal road project with 86% description overlap (recomputed live from both descriptions).",
    mpPlainStatus: "Held due to 86% duplicate match with existing road work in Pragathi Nagar.",
    compositeScore: 82,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("duplicate", 87, "Text similarity 86% to ‘Laying of CC Road and Storm Drain’ 210 m away.", true, {
        kind: "duplicate",
        twinTitle: "Laying of CC Road and Storm Drain, Pragathi Nagar, Medchal",
        twinId: "MPL-2025-1004",
        distanceMeters: 210,
        textSimilarityPct: 86,
        mapX: 62,
        mapY: 38,
      }),
      mod("cost", 28, "Cost estimate slightly above median."),
      mod("compliance", 10, "Municipal road corridor verified."),
      mod("payment", 8, "Initial stage."),
      mod("predictive", 18, "Moderate delay risk."),
      mod("photo", 0, "No photo violation."),
      mod("trend", 30, "Pace within district band."),
    ],
  },

  /* 4 — Twin of #3 (Medchal-Malkajgiri) */
  {
    id: "MPL-2025-1004",
    title: "Laying of CC Road and Storm Drain, Pragathi Nagar, Medchal",
    hindiTitle: "सीसी सड़क एवं नाली बिछाना, प्रगति नगर, मेडचल",
    category: "Rural Roads",
    state: STATE_NAME,
    district: "Medchal-Malkajgiri",
    constituency: "Malkajgiri",
    mpName: "Shri Eatala Rajender",
    dmName: "DM Iyer (Demo)",
    sanctionedAmountLakh: 22.5,
    sanctionedDate: "15 Feb 2025",
    status: "released",
    statusSince: "10 Mar 2025",
    overview: "Original sanctioned CC road work at Pragathi Nagar in advanced construction stage.",
    mpPlainStatus: "Work executing on schedule with regular inspection milestones.",
    compositeScore: 16,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 6, "Clear of duplicate conflicts."),
      mod("cost", 14, "Standard PWD schedule pricing."),
      mod("compliance", 10, "Public right of way."),
      mod("payment", 10, "Disbursements match physical execution."),
      mod("predictive", 5, "Low risk."),
      mod("photo", 4, "Geotagged verified photos."),
      mod("trend", 18, "Normal disbursal trend."),
    ],
  },

  /* 5 — Cost Outlier (Sangareddy - Z-score +3.45) */
  {
    id: "MPL-2025-1005",
    title: "Rural Link CC Road, Zaheerabad to Kohir Feeder km 0-3.5, Sangareddy",
    hindiTitle: "ग्रामीण लिंक सीसी रोड, जहीराबाद से कोहिर फीडर किमी 0-3.5",
    category: "Rural Roads",
    state: STATE_NAME,
    district: "Sangareddy",
    constituency: "Zaheerabad",
    mpName: "Shri Harish Chandran (Demo Constituency)",
    dmName: "DM Nair (Demo)",
    sanctionedAmountLakh: 48.5,
    sanctionedDate: "02 May 2025",
    status: "escalated",
    statusSince: "22 Jun 2025",
    overview: "Sanctioned at ₹48.5 Lakh against district median baseline of ₹22.0 Lakh for comparable rural road works. Robust MAD Z-score is +3.45.",
    mpPlainStatus: "Escalated to engineering audit due to cost variance (+120% above district benchmark).",
    compositeScore: 76,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active", "escalated"],
    moduleBreakdown: [
      mod("cost", 86, "Sanctioned ₹48.5L vs peer band 16–29L (Z-score +3.45) — extreme cost anomaly.", true, {
        kind: "cost",
        sanctionedLakh: 48.5,
        peerLowLakh: 16.0,
        peerHighLakh: 29.0,
        peerMeanLakh: 22.0,
        zScore: 3.45,
        categoryLabel: "Rural Roads in Sangareddy",
      }),
      mod("duplicate", 6, "No duplicate work found."),
      mod("compliance", 30, "BOQ benchmarking failed standard Schedule of Rates."),
      mod("payment", 25, "Slow initial drawdown."),
      mod("predictive", 45, "High probability of cost-driven contract disputes."),
      mod("photo", 0, "No photo violation."),
      mod("trend", 35, "Lagging peer disbursal pace."),
    ],
  },

  /* 6 — Cost Outlier (Mahbubnagar - Z-score +3.32) */
  {
    id: "MPL-2025-1006",
    title: "High-Mast Solar LED Streetlighting Array, Jadcherla Junction, Mahbubnagar",
    hindiTitle: "हाई-मास्ट सोलर एलईडी स्ट्रीटलाइटिंग, जदचेरला जंक्शन",
    category: "Renewable Energy",
    state: STATE_NAME,
    district: "Mahbubnagar",
    constituency: "Mahbubnagar",
    mpName: "Smt. Devika Balan (Demo Constituency)",
    dmName: "DM Rao (Demo)",
    sanctionedAmountLakh: 36.0,
    sanctionedDate: "14 Apr 2025",
    status: "hold_active",
    statusSince: "28 May 2025",
    overview: "Sanctioned ₹36.0 Lakh for 10 solar LED mast units against benchmark median of ₹14.0 Lakh. Robust Z-score is +3.32.",
    mpPlainStatus: "Held for cost re-verification — unit rates are 157% higher than TSREDCO approved tariffs.",
    compositeScore: 72,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("cost", 82, "Sanctioned ₹36.0L vs peer band 9–19L (Z-score +3.32) — cost estimate outlier.", true, {
        kind: "cost",
        sanctionedLakh: 36.0,
        peerLowLakh: 9.0,
        peerHighLakh: 19.0,
        peerMeanLakh: 14.0,
        zScore: 3.32,
        categoryLabel: "Renewable Energy in Mahbubnagar",
      }),
      mod("duplicate", 8, "No duplicate match."),
      mod("compliance", 28, "Non-standard procurement pricing."),
      mod("payment", 10, "Initial stage."),
      mod("predictive", 38, "Vendor quote dispute risk."),
      mod("photo", 0, "No photo flags."),
      mod("trend", 25, "Normal pace."),
    ],
  },

  /* 7 — Hard-Gate Violation 1 (Rangareddy - Non-Public Land Tenure) */
  {
    id: "MPL-2025-1007",
    title: "Community Function Hall at Sri Sai Enclave, Rajendranagar, Rangareddy",
    hindiTitle: "सामुदायिक भवन, श्री साई एन्क्लेव, राजेंद्रनगर",
    category: "Community Assets",
    state: STATE_NAME,
    district: "Rangareddy",
    constituency: "Chevella",
    mpName: "Shri Anant Rao (Demo Constituency)",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 28.0,
    sanctionedDate: "05 Jun 2025",
    status: "hold_active",
    statusSince: "12 Jun 2025",
    overview: "CRITICAL COMPLIANCE GATE FIRED: Proposal site is situated on private un-regularised society land. MPLADS guidelines mandate clear public/municipal ownership.",
    mpPlainStatus: "HARD GATE HOLD: Cannot proceed because land is private/un-regularised. Requires public title conveyance.",
    compositeScore: 94,
    gate: {
      fired: true,
      rule: "Mandatory compliance guardrail failed: Non-public land tenure.",
      detail: "Asset proposed on private gated layout (Sy No. 142/A). Prohibited under §4.1.3.",
      heldIndependent: true,
    },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("compliance", 95, "2 mandatory guardrails failing — Land ownership: Private gated society land.", true, {
        kind: "compliance",
        field: "Land ownership",
        actual: "Private gated society land (Sy No. 142/A)",
        required: "Public / Municipal Land",
        ruleRef: "OP 2025–26 §4.1.3",
        clauseText: "MPLADS funds can only create assets on land belonging to Government or local body.",
      }),
      mod("cost", 20, "Cost estimate within norms."),
      mod("duplicate", 10, "No spatial duplicate."),
      mod("payment", 10, "No releases processed."),
      mod("predictive", 70, "Title dispute will prevent asset handover."),
      mod("photo", 0, "No photo issues."),
      mod("trend", 15, "Normal window."),
    ],
  },

  /* 8 — Hard-Gate Violation 2 (Hyderabad - Forged Stage Photo pHash >= 99%) */
  {
    id: "MPL-2025-1008",
    title: "Modernization of Urban Health Post, Yakutpura, Hyderabad",
    hindiTitle: "शहरी स्वास्थ्य केंद्र का आधुनिकीकरण, याकूतपुरा",
    category: "Health & Sanitation",
    state: STATE_NAME,
    district: "Hyderabad",
    constituency: "Hyderabad",
    mpName: "Shri Vikram Rathore (Demo Constituency)",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 19.5,
    sanctionedDate: "18 Mar 2025",
    status: "hold_active",
    statusSince: "25 May 2025",
    overview: "CRITICAL PHOTO GATE FIRED: Uploaded Stage-2 completion photographs match photos submitted under MPL-2024-0341 with 99.6% perceptual hash similarity.",
    mpPlainStatus: "HARD GATE HOLD: Uploaded site inspection photo is identical to a prior year clinic in another ward.",
    compositeScore: 88,
    gate: {
      fired: true,
      rule: "High-confidence photo-integrity violation (pHash match ≥ 99%).",
      detail: "Uploaded photograph identical to MPL-2024-0341. Suspicion of staged/reused submission.",
      heldIndependent: true,
    },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("photo", 98, "pHash 99.6% match to existing completed work photo from MPL-2024-0341.", true, {
        kind: "photo",
        photos: [
          { label: "This work (Stage 2)", color: "#b42318", pHash: "f3c8a1b2d9e074a3" },
          { label: "Twin work (MPL-2024-0341)", color: "#143560", pHash: "f3c8a1b2d9e074a3" },
        ],
        pHashMatchPct: 99.6,
        exif: [
          { field: "Camera Body", photoA: "Canon EOS 1500D (SN: 34091)", photoB: "Canon EOS 1500D (SN: 34091)", corroborating: true },
          { field: "GPS Coordinates", photoA: "17.3616° N, 78.4747° E", photoB: "17.3616° N, 78.4747° E", corroborating: true },
        ],
      }),
      mod("compliance", 45, "Photographic stage verification failed §8.3."),
      mod("payment", 50, "50% funds released with suspected falsified progress."),
      mod("cost", 18, "Normal estimate."),
      mod("duplicate", 12, "No title duplicate."),
      mod("predictive", 55, "Severe compliance stall risk."),
      mod("trend", 20, "Normal timeline."),
    ],
  },

  /* 9 — Ghost Completion Case (Sangareddy - 90% released, 10% progress) */
  {
    id: "MPL-2025-1009",
    title: "Construction of Skill Training Centre & Workshop, Patancheru, Sangareddy",
    hindiTitle: "कौशल प्रशिक्षण केंद्र एवं कार्यशाला, पाटनचेरु",
    category: "Social Infrastructure",
    state: STATE_NAME,
    district: "Sangareddy",
    constituency: "Medak",
    mpName: "Shri Harish Chandran (Demo Constituency)",
    dmName: "DM Nair (Demo)",
    sanctionedAmountLakh: 38.0,
    sanctionedDate: "10 Nov 2024",
    status: "hold_active",
    statusSince: "15 Aug 2025",
    overview: "GHOST COMPLETION DETECTED: 90% (₹34.2L) of funds disbursed through 3 installments while ground physical progress remains at only 10% foundation level after 9 months.",
    mpPlainStatus: "Held for physical vigilance audit: 90% funds drawn while only foundation pillars exist on ground.",
    compositeScore: 84,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("payment", 94, "100% of funds released with only 10% physical completion (9 months) — suspected ghost completion.", true),
      mod("predictive", 78, "Severe payment vs progress divergence; contract stall risk extreme.", true, {
        kind: "predictive",
        stallProbabilityPct: 78,
        factors: ["Severe payment vs progress divergence", "No contractor milestone submission in 120 days", "Measurement book uncertified"],
      }),
      mod("compliance", 35, "Measurement Book un-certified for Stage 3."),
      mod("cost", 24, "Cost within range."),
      mod("duplicate", 5, "No duplicate."),
      mod("photo", 20, "Ground photos show only foundation work."),
      mod("trend", 45, "Excessive front-loaded disbursals."),
    ],
  },

  /* 10 — PFMS Fund Redirection Alert Case (Medchal-Malkajgiri) */
  {
    id: "MPL-2025-1010",
    title: "Establishment of RO Drinking Water Plant (1000 LPH), Ghatkesar, Medchal",
    hindiTitle: "आरओ पेयजल संयंत्र की स्थापना (1000 LPH), घटकेसर",
    category: "Drinking Water",
    state: STATE_NAME,
    district: "Medchal-Malkajgiri",
    constituency: "Malkajgiri",
    mpName: "Shri Vikram Rathore (Demo Constituency)",
    dmName: "DM Iyer (Demo)",
    sanctionedAmountLakh: 11.5,
    sanctionedDate: "08 Feb 2025",
    status: "hold_active",
    statusSince: "14 Apr 2025",
    overview: "PFMS INTEGRITY ALERT: Stage-2 fund release was requested to an un-bound bank account differing from the dedicated Stage-1 Implementing Agency account.",
    mpPlainStatus: "Held for vendor reconciliation: Stage 2 payment account changed without logged administrative approval.",
    compositeScore: 74,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "hold_active"],
    facts: {
      pfms: {
        stage_number: 2,
        stage1_account: "SBIN00014239871",
        target_account: "HDFC00098471204",
        vendor_gstin: "36AAAGW2345Q1Z6",
        vendor_name: "Rural Water Supply & Sanitation Department",
      },
    },
    moduleBreakdown: [
      mod("payment", 80, "Stage 2 disbursement account does not match Stage 1 registered agency account. Instant FUND_REDIRECTION_ALERT raised.", true, {
        kind: "pfms",
        stageNumber: 2,
        accountMatch: false,
        fundRedirectionAlert: true,
        vendorSimilarityPct: 100.0,
        vendorMatchedName: "Rural Water Supply & Sanitation Department",
        flags: ["FUND_REDIRECTION_ALERT"],
        detail: "Stage 2 disbursement account (*******1204) does not match Stage 1 registered agency account (*******9871). Instant FUND_REDIRECTION_ALERT raised.",
      }),
      mod("compliance", 30, "PFMS Single Nodal Account binding violation."),
      mod("cost", 15, "Standard RO plant unit pricing."),
      mod("duplicate", 5, "No duplicate."),
      mod("predictive", 22, "Moderate risk."),
      mod("photo", 0, "No photo issues."),
      mod("trend", 20, "Normal timeline."),
    ],
  },

  /* 11 — Clean Case: Solar High Mast Array (Rangareddy) */
  {
    id: "MPL-2025-1011",
    title: "Solar LED Street Light Installation across 8 Gram Panchayats, Shamshabad, Rangareddy",
    hindiTitle: "8 ग्राम पंचायतों में सोलर एलईडी स्ट्रीट लाइट स्थापना, शमशाबाद",
    category: "Renewable Energy",
    state: STATE_NAME,
    district: "Rangareddy",
    constituency: "Chevella",
    mpName: "Shri Konda Vishweshwar Reddy",
    dmName: "DM Verma (Demo)",
    sanctionedAmountLakh: 18.0,
    sanctionedDate: "20 Jan 2025",
    status: "released",
    statusSince: "15 May 2025",
    overview: "Solar illumination project executed by TSREDCO. All 80 fixtures commissioned, geotagged, and verified clean.",
    mpPlainStatus: "Project 100% completed and handed over to local panchayats.",
    compositeScore: 10,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 4, "No duplicate."),
      mod("cost", 10, "TSREDCO schedule compliant."),
      mod("compliance", 10, "Public right of way cleared."),
      mod("payment", 8, "100% funds released matching 100% completion."),
      mod("predictive", 2, "Completed."),
      mod("photo", 2, "All 80 fixtures verified on site."),
      mod("trend", 10, "On schedule."),
    ],
  },

  /* 12 — Clean Case: High School STEM Lab (Hyderabad) */
  {
    id: "MPL-2025-1012",
    title: "Modern Science & Robotics Lab, Govt High School, Khairatabad, Hyderabad",
    hindiTitle: "आधुनिक विज्ञान एवं रोबोटिक्स लैब, सरकारी उच्च विद्यालय, खैरताबाद",
    category: "Education",
    state: STATE_NAME,
    district: "Hyderabad",
    constituency: "Secunderabad",
    mpName: "Shri G. Kishan Reddy",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 22.0,
    sanctionedDate: "14 Feb 2025",
    status: "released",
    statusSince: "28 Jun 2025",
    overview: "State-of-the-art STEM equipment, smart boards, and laboratory benches supplied and installed under Education Department supervision.",
    mpPlainStatus: "Completed and in active use by 650 students.",
    compositeScore: 12,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 4, "Unique educational asset."),
      mod("cost", 12, "Within CPWD school standards."),
      mod("compliance", 10, "Government school property."),
      mod("payment", 10, "Handover complete."),
      mod("predictive", 3, "Operational."),
      mod("photo", 4, "Geotagged lab installation photos verified."),
      mod("trend", 14, "On track."),
    ],
  },

  /* 13 — Clean Case: Primary Health Centre Triage Extension (Mahbubnagar) */
  {
    id: "MPL-2025-1013",
    title: "Emergency Ambulance Shed & Triage Extension, CHC Bhoothpur, Mahbubnagar",
    hindiTitle: "आपातकालीन एम्बुलेंस शेड एवं ट्राइएज विस्तार, सामुदायिक स्वास्थ्य केंद्र",
    category: "Health & Sanitation",
    state: STATE_NAME,
    district: "Mahbubnagar",
    constituency: "Mahbubnagar",
    mpName: "Smt. D. K. Aruna",
    dmName: "DM Rao (Demo)",
    sanctionedAmountLakh: 14.2,
    sanctionedDate: "18 Mar 2025",
    status: "released",
    statusSince: "05 Jul 2025",
    overview: "Civil structural expansion of primary health triage bay completed within technical budget estimates.",
    mpPlainStatus: "Civil works completed on schedule. Operational.",
    compositeScore: 15,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 5, "No duplicate."),
      mod("cost", 14, "State medical board rates."),
      mod("compliance", 10, "Hospital campus."),
      mod("payment", 12, "Milestones on track."),
      mod("predictive", 6, "Low risk."),
      mod("photo", 5, "Clean stage photos."),
      mod("trend", 15, "Normal trend."),
    ],
  },

  /* 14 — Evaluating Case: Anganwadi Centre Building (Rangareddy) */
  {
    id: "MPL-2025-1014",
    title: "Construction of Model Anganwadi Centre, Ibrahimpatnam, Rangareddy",
    hindiTitle: "मॉडल आंगनवाड़ी केंद्र का निर्माण, इब्राहिमपटनम",
    category: "Social Infrastructure",
    state: STATE_NAME,
    district: "Rangareddy",
    constituency: "Chevella",
    mpName: "Shri Konda Vishweshwar Reddy",
    dmName: "DM Verma (Demo)",
    sanctionedAmountLakh: 13.5,
    sanctionedDate: "01 Aug 2025",
    status: "evaluating",
    statusSince: "01 Aug 2025",
    overview: "New proposal submitted by Women & Child Welfare dept; automated guardrail and cost baseline checks currently running clean.",
    mpPlainStatus: "Under normal administrative clearance and technical evaluation.",
    compositeScore: 18,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating"],
    moduleBreakdown: [
      mod("duplicate", 8, "No duplicate within 500m."),
      mod("cost", 16, "Standard rural building SOR."),
      mod("compliance", 10, "Revenue patta verified."),
      mod("payment", 10, "Pending initial mobilization."),
      mod("predictive", 8, "Clean parameters."),
      mod("photo", 0, "Pre-construction site geotagged."),
      mod("trend", 15, "Evaluation phase."),
    ],
  },

  /* 15 — Evaluating Case: Drinking Water Pipe Network (Sangareddy) */
  {
    id: "MPL-2025-1015",
    title: "Drinking Water Pipeline Network Extension, Sadasivpet, Sangareddy",
    hindiTitle: "पेयजल पाइपलाइन नेटवर्क विस्तार, सदाशिवपेट",
    category: "Drinking Water",
    state: STATE_NAME,
    district: "Sangareddy",
    constituency: "Zaheerabad",
    mpName: "Shri Suresh Kumar Shetkar",
    dmName: "DM Nair (Demo)",
    sanctionedAmountLakh: 21.0,
    sanctionedDate: "22 Jul 2025",
    status: "evaluating",
    statusSince: "22 Jul 2025",
    overview: "Pipeline interconnection project with Mission Bhagiratha grid. Technical sanction and BOQ verified aligned with schedule.",
    mpPlainStatus: "Under administrative verification with Mission Bhagiratha engineers.",
    compositeScore: 20,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating"],
    moduleBreakdown: [
      mod("duplicate", 10, "No duplicate."),
      mod("cost", 18, "Mission Bhagiratha rates."),
      mod("compliance", 10, "Public right of way."),
      mod("payment", 10, "Initial stage."),
      mod("predictive", 10, "Normal."),
      mod("photo", 0, "Pre-construction survey."),
      mod("trend", 18, "Pacing on track."),
    ],
  },

  /* 16 — Clean Case: Crematorium Shed (Mahbubnagar) */
  {
    id: "MPL-2025-1016",
    title: "Vaikunta Dhamam Crematorium Shed & High-Mast Solar Light, Devarakadra, Mahbubnagar",
    hindiTitle: "वैकुंठ धाम शवदाह गृह शेड एवं सोलर लाइट, देवरकद्र",
    category: "Community Assets",
    state: STATE_NAME,
    district: "Mahbubnagar",
    constituency: "Mahbubnagar",
    mpName: "Smt. D. K. Aruna",
    dmName: "DM Rao (Demo)",
    sanctionedAmountLakh: 17.5,
    sanctionedDate: "10 Mar 2025",
    status: "released",
    statusSince: "25 May 2025",
    overview: "Model rural crematorium facility completed with concrete shed, solar lighting, and dedicated water tank.",
    mpPlainStatus: "Civil work 100% completed and handed over.",
    compositeScore: 11,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 5, "No twin."),
      mod("cost", 12, "Standard rates."),
      mod("compliance", 10, "Gram panchayat land."),
      mod("payment", 8, "Completed."),
      mod("predictive", 4, "Zero risk."),
      mod("photo", 3, "Handover photos verified."),
      mod("trend", 12, "On schedule."),
    ],
  },

  /* 17 — Clean Case: High School Classrooms (Medchal-Malkajgiri) */
  {
    id: "MPL-2025-1017",
    title: "Construction of 2 Additional Classrooms, ZP High School, Alwal, Medchal",
    hindiTitle: "2 अतिरिक्त कक्षाओं का निर्माण, जिला परिषद हाई स्कूल, अलवाल",
    category: "Education",
    state: STATE_NAME,
    district: "Medchal-Malkajgiri",
    constituency: "Malkajgiri",
    mpName: "Shri Eatala Rajender",
    dmName: "DM Iyer (Demo)",
    sanctionedAmountLakh: 19.8,
    sanctionedDate: "05 Jan 2025",
    status: "released",
    statusSince: "15 Apr 2025",
    overview: "Two classroom block completed with dual desk benches, ceiling fans, and LED fixtures.",
    mpPlainStatus: "Classrooms completed and operational for academic session.",
    compositeScore: 9,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 4, "No duplicate."),
      mod("cost", 10, "Education engineering cell rates."),
      mod("compliance", 10, "School property."),
      mod("payment", 8, "All milestones verified."),
      mod("predictive", 2, "Complete."),
      mod("photo", 3, "Classroom photos clean."),
      mod("trend", 10, "Smooth progress."),
    ],
  },

  /* 18 — Clean Case: CC Drain Construction (Hyderabad) */
  {
    id: "MPL-2025-1018",
    title: "Construction of RCC Underground Storm Drain, Musheerabad, Hyderabad",
    hindiTitle: "आरसीसी भूमिगत वर्षा जल नाली निर्माण, मुशीराबाद",
    category: "Rural Roads",
    state: STATE_NAME,
    district: "Hyderabad",
    constituency: "Secunderabad",
    mpName: "Shri G. Kishan Reddy",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 27.5,
    sanctionedDate: "12 Feb 2025",
    status: "released",
    statusSince: "18 May 2025",
    overview: "GHMC drainage expansion preventing seasonal waterlogging at Musheerabad junction.",
    mpPlainStatus: "Completed ahead of monsoon schedule.",
    compositeScore: 14,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 6, "No duplicate."),
      mod("cost", 15, "GHMC engineering rates."),
      mod("compliance", 10, "Municipal road corridor."),
      mod("payment", 12, "Disbursements verified."),
      mod("predictive", 5, "Low risk."),
      mod("photo", 5, "Site completion confirmed."),
      mod("trend", 15, "Normal pace."),
    ],
  },

  /* 19 — Evaluating Case: Women SHG Skill Centre (Sangareddy) */
  {
    id: "MPL-2025-1019",
    title: "Establishment of Mahila Samakhya Livelihood Training Centre, Narayankhed, Sangareddy",
    hindiTitle: "महिला समाख्या आजीविका प्रशिक्षण केंद्र, नारायणखेड़",
    category: "Social Infrastructure",
    state: STATE_NAME,
    district: "Sangareddy",
    constituency: "Zaheerabad",
    mpName: "Shri Suresh Kumar Shetkar",
    dmName: "DM Nair (Demo)",
    sanctionedAmountLakh: 15.0,
    sanctionedDate: "18 Aug 2025",
    status: "evaluating",
    statusSince: "18 Aug 2025",
    overview: "Proposal for sewing, handicrafts, and digital literacy training unit for rural self-help groups.",
    mpPlainStatus: "Under administrative review by DRDA / District Collectorate.",
    compositeScore: 16,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating"],
    moduleBreakdown: [
      mod("duplicate", 6, "No duplicate."),
      mod("cost", 14, "Standard community asset rate."),
      mod("compliance", 10, "DRDA building."),
      mod("payment", 8, "Initial stage."),
      mod("predictive", 5, "Low risk."),
      mod("photo", 0, "Initial survey."),
      mod("trend", 12, "On schedule."),
    ],
  },

  /* 20 — Clean Case: Community RO Drinking Water Kiosk (Rangareddy) */
  {
    id: "MPL-2025-1020",
    title: "Community RO Drinking Water Kiosk (500 LPH), Maheshwaram, Rangareddy",
    hindiTitle: "सामुदायिक आरओ पेयजल कियोस्क (500 LPH), महेश्वरम",
    category: "Drinking Water",
    state: STATE_NAME,
    district: "Rangareddy",
    constituency: "Chevella",
    mpName: "Shri Konda Vishweshwar Reddy",
    dmName: "DM Verma (Demo)",
    sanctionedAmountLakh: 8.5,
    sanctionedDate: "04 Mar 2025",
    status: "released",
    statusSince: "22 Jun 2025",
    overview: "Purified safe drinking water facility providing 20L cans to 400 rural households daily.",
    mpPlainStatus: "Fully commissioned and serving drinking water to village community.",
    compositeScore: 8,
    gate: { fired: false, heldIndependent: false },
    path: ["submitted", "evaluating", "released"],
    moduleBreakdown: [
      mod("duplicate", 4, "No duplicate within 500m."),
      mod("cost", 8, "Clean unit pricing."),
      mod("compliance", 10, "Gram panchayat compound."),
      mod("payment", 6, "100% completed & handed over."),
      mod("predictive", 2, "Zero stall risk."),
      mod("photo", 2, "Commissioning photos geotagged."),
      mod("trend", 8, "Completed ahead of time."),
    ],
  },

  /* 21 — Un-suspecting Gate-Fired Case: composite only 30/100, yet the Land Tenure
     hard gate fired and holds the work independently of the fusion score. */
  {
    id: "MPL-2025-1021",
    title: "Community Meeting Shed & Drinking Water Shelter, Sy. No. 298, Shamshabad, Rangareddy",
    hindiTitle: "सामुदायिक बैठक शेड एवं पेयजल शेल्टर, सर्वे नं. 298, शमशाबाद",
    category: "Community Assets",
    state: STATE_NAME,
    district: "Rangareddy",
    constituency: "Chevella",
    mpName: "Shri Anant Rao (Demo Constituency)",
    dmName: "DM Sharma (Demo)",
    sanctionedAmountLakh: 14.0,
    sanctionedDate: "07 Jul 2025",
    status: "hold_active",
    statusSince: "07 Jul 2025",
    overview:
      "GATE FIRED ON AN OTHERWISE LOW-RISK CASE: the proposed site is a private gated society plot (Sy. No. 298/A), not public or municipal land, so the Critical-Risk Gate holds the work even though the composite risk score is only 30/100.",
    mpPlainStatus:
      "HARD GATE HOLD: Land tenure is private/un-regularised. This is not a threshold alert — it can only be waived against the record as a Gate Override.",
    compositeScore: 30,
    gate: {
      fired: true,
      rule: "a mandatory compliance guardrail failed (governs land tenure, entity type, safety certification)",
      detail: "Asset proposed on private gated layout (Sy. No. 298/A). Prohibited under OP 2025–26 §4.1.3.",
      heldIndependent: true,
    },
    path: ["submitted", "evaluating", "hold_active"],
    moduleBreakdown: [
      mod("compliance", 65, "1 mandatory guardrail failing — Land ownership: Private gated society land.", true, {
        kind: "compliance",
        field: "Land ownership",
        actual: "Private gated society land (Sy. No. 298/A)",
        required: "Public / Municipal Land",
        ruleRef: "OP 2025–26 §4.1.3",
        clauseText:
          "MPLADS funds can only create assets on land belonging to Government or a local body; private/un-regularised plots are ineligible.",
      }),
      mod("cost", 24, "Sanctioned ₹14.0 L vs cohort median ₹16.5 L — within distribution.", false, {
        kind: "cost",
        sanctionedLakh: 14.0,
        peerLowLakh: 11.0,
        peerHighLakh: 24.0,
        peerMeanLakh: 16.5,
        zScore: -0.33,
        categoryLabel: "Community Assets",
      }),
      mod("payment", 32, "Releases track physical progress within norms."),
      mod("predictive", 20, "10% predicted probability of stalling — within norms.", false, {
        kind: "predictive",
        stallProbabilityPct: 10,
        factors: [],
      }),
      mod("duplicate", 6, "No vendor duplicate within similarity/geographic thresholds."),
      mod("trend", 10, "Release pace within same-cohort peers."),
      mod("photo", 4, "No stage photographs uploaded for this work."),
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Ledger Seeds with Cryptographic Hashes                             */
/* ------------------------------------------------------------------ */

interface RawLedgerSeed {
  action: string;
  category: LedgerCategory;
  actor: string;
  actorRole: string;
  body: string;
  timestamp: string;
  caseId?: string;
}

const rawLedgerSeeds: RawLedgerSeed[] = [
  {
    action: "GENESIS BLOCK",
    category: "genesis",
    actor: "system",
    actorRole: "Sentinel Genesis Authority",
    body: "MPLADS Sentinel Cryptographic Audit Chain Initialized for Telangana State.",
    timestamp: "2025-01-01T00:00:00",
  },
  {
    action: "PROPOSAL INGESTED",
    category: "submit",
    actor: "system",
    actorRole: "Sentinel Ingestion Engine",
    body: "eSAKSHI Work MPL-2025-1002 ingested & verified clean. Composite Risk: 14/100.",
    timestamp: "2025-01-10T10:15:00",
    caseId: "MPL-2025-1002",
  },
  {
    action: "GATE HOLD FIRED",
    category: "hold",
    actor: "system",
    actorRole: "Sentinel Circuit Breaker Gate",
    body: "Hard Gate M9 triggered on MPL-2025-1007: Private land tenure detected.",
    timestamp: "2025-06-05T14:30:00",
    caseId: "MPL-2025-1007",
  },
  {
    action: "PHOTO GATE FIRED",
    category: "hold",
    actor: "system",
    actorRole: "Sentinel Circuit Breaker Gate",
    body: "Hard Gate M9 triggered on MPL-2025-1008: Stage photo pHash match 99.6% vs prior work.",
    timestamp: "2025-05-25T11:45:00",
    caseId: "MPL-2025-1008",
  },
  {
    action: "ESCALATED TO AUDIT",
    category: "escalate",
    actor: "dm_sangareddy",
    actorRole: "District Magistrate, Sangareddy",
    body: "Escalated MPL-2025-1005 to State Engineering Auditor for BOQ inflation review.",
    timestamp: "2025-06-22T16:00:00",
    caseId: "MPL-2025-1005",
  },
];

export function buildLedger(): LedgerEntry[] {
  const result: LedgerEntry[] = [];
  let prev = "0".repeat(16);
  for (let i = 0; i < rawLedgerSeeds.length; i++) {
    const s = rawLedgerSeeds[i];
    const hash = ledgerHash(prev, i, s.action, s.actor, s.body, s.timestamp);
    result.push({
      index: i,
      action: s.action,
      category: s.category,
      actor: s.actor,
      actorRole: s.actorRole,
      body: s.body,
      timestamp: s.timestamp,
      caseId: s.caseId,
      hash,
      prevHash: prev,
    });
    prev = hash;
  }
  return result;
}

/* ------------------------------------------------------------------ */
/* Officials & Override Oversight Register                             */
/* ------------------------------------------------------------------ */

export const baseOfficials: OfficialStat[] = [
  {
    id: "off-1",
    name: "DM Sharma (Demo)",
    role: "District Collector & Magistrate",
    district: "Hyderabad",
    state: STATE_NAME,
    highRiskDecisions: 4,
    gateOverrides: 0,
    thresholdOverrides: 1,
    flaggedNote: "Rigorous adherence to compliance gate protocols.",
  },
  {
    id: "off-2",
    name: "DM Verma (Demo)",
    role: "District Collector & Magistrate",
    district: "Rangareddy",
    state: STATE_NAME,
    highRiskDecisions: 5,
    gateOverrides: 0,
    thresholdOverrides: 2,
    flaggedNote: "Active monitoring on land regularisation checks.",
  },
  {
    id: "off-3",
    name: "DM Iyer (Demo)",
    role: "District Collector & Magistrate",
    district: "Medchal-Malkajgiri",
    state: STATE_NAME,
    highRiskDecisions: 6,
    gateOverrides: 1,
    thresholdOverrides: 2,
    flaggedNote: "1 Gate override under scrutiny for vendor binding.",
  },
  {
    id: "off-4",
    name: "DM Nair (Demo)",
    role: "District Collector & Magistrate",
    district: "Sangareddy",
    state: STATE_NAME,
    highRiskDecisions: 7,
    gateOverrides: 0,
    thresholdOverrides: 3,
    flaggedNote: "Elevated threshold override rate on road infrastructure.",
  },
  {
    id: "off-5",
    name: "DM Rao (Demo)",
    role: "District Collector & Magistrate",
    district: "Mahbubnagar",
    state: STATE_NAME,
    highRiskDecisions: 3,
    gateOverrides: 0,
    thresholdOverrides: 1,
    flaggedNote: "Cost variance holds strictly enforced.",
  },
];

/* ------------------------------------------------------------------ */
/* Analytics & Dashboard Benchmarks                                   */
/* ------------------------------------------------------------------ */

export const analyticsMock: AnalyticsData = {
  // Official MoSPI “Allocated Limit for Hon'ble MPs” — generated from the
  // vendored CSV (backend/app/data/mp_allocations_2025.csv); identical to
  // what the live API serves from the DB.
  mpAllocations: {
    source: "Official MoSPI allocation table — “Allocated Limit for Hon'ble MPs”",
    mpCount: MP_ALLOCATIONS.length,
    totalCr: MP_ALLOCATION_TOTAL_CR,
    mps: MP_ALLOCATIONS,
  },
  districtUtilization: [
    { district: "Hyderabad", q1: 88, q2: 92, q3: 85, q4: 90, ytd: 89 },
    { district: "Rangareddy", q1: 78, q2: 84, q3: 80, q4: 86, ytd: 82 },
    { district: "Medchal-Malkajgiri", q1: 82, q2: 80, q3: 76, q4: 85, ytd: 81 },
    { district: "Sangareddy", q1: 65, q2: 70, q3: 62, q4: 74, ytd: 68 },
    { district: "Mahbubnagar", q1: 70, q2: 72, q3: 68, q4: 76, ytd: 72 },
  ],
  districtTrend: [
    { month: "Apr", Hyderabad: 18, Rangareddy: 15, "Medchal-Malkajgiri": 16, Sangareddy: 12, Mahbubnagar: 14 },
    { month: "May", Hyderabad: 36, Rangareddy: 32, "Medchal-Malkajgiri": 30, Sangareddy: 24, Mahbubnagar: 26 },
    { month: "Jun", Hyderabad: 54, Rangareddy: 48, "Medchal-Malkajgiri": 49, Sangareddy: 38, Mahbubnagar: 42 },
    { month: "Jul", Hyderabad: 72, Rangareddy: 65, "Medchal-Malkajgiri": 66, Sangareddy: 52, Mahbubnagar: 58 },
    { month: "Aug", Hyderabad: 89, Rangareddy: 82, "Medchal-Malkajgiri": 81, Sangareddy: 68, Mahbubnagar: 72 },
  ],
  nationalHeatmap: [
    { state: "Telangana", utilization: 84, cases: 20 },
    { state: "Andhra Pradesh", utilization: 81, cases: 18 },
    { state: "Karnataka", utilization: 86, cases: 24 },
    { state: "Maharashtra", utilization: 79, cases: 28 },
    { state: "Tamil Nadu", utilization: 88, cases: 26 },
  ],
  categoryExpenditure: [
    { category: "Rural Roads", sanctionsCr: 14.8, releasesCr: 12.1 },
    { category: "Community Assets", sanctionsCr: 11.2, releasesCr: 9.4 },
    { category: "Drinking Water", sanctionsCr: 8.6, releasesCr: 7.3 },
    { category: "Education", sanctionsCr: 9.4, releasesCr: 8.0 },
    { category: "Health & Sanitation", sanctionsCr: 7.8, releasesCr: 6.5 },
    { category: "Renewable Energy", sanctionsCr: 6.2, releasesCr: 5.4 },
    { category: "Social Infrastructure", sanctionsCr: 5.5, releasesCr: 4.6 },
  ],
  entitlements: [
    {
      mpName: "Shri G. Kishan Reddy",
      annualCr: 5.0,
      usedCr: 4.82,
      breakdown: [
        { category: "Education", lakh: 145 },
        { category: "Community Assets", lakh: 162 },
        { category: "Health & Sanitation", lakh: 95 },
        { category: "Rural Roads", lakh: 80 },
      ],
    },
    {
      mpName: "Shri Eatala Rajender",
      annualCr: 5.0,
      usedCr: 4.45,
      breakdown: [
        { category: "Rural Roads", lakh: 185 },
        { category: "Drinking Water", lakh: 95 },
        { category: "Education", lakh: 115 },
        { category: "Community Assets", lakh: 50 },
      ],
    },
    {
      mpName: "Shri Konda Vishweshwar Reddy",
      annualCr: 5.0,
      usedCr: 4.60,
      breakdown: [
        { category: "Renewable Energy", lakh: 120 },
        { category: "Drinking Water", lakh: 90 },
        { category: "Community Assets", lakh: 150 },
        { category: "Social Infrastructure", lakh: 100 },
      ],
    },
    {
      mpName: "Shri Suresh Kumar Shetkar",
      annualCr: 5.0,
      usedCr: 3.90,
      breakdown: [
        { category: "Rural Roads", lakh: 210 },
        { category: "Drinking Water", lakh: 95 },
        { category: "Social Infrastructure", lakh: 85 },
      ],
    },
    {
      mpName: "Smt. D. K. Aruna",
      annualCr: 5.0,
      usedCr: 4.15,
      breakdown: [
        { category: "Health & Sanitation", lakh: 135 },
        { category: "Renewable Energy", lakh: 110 },
        { category: "Community Assets", lakh: 120 },
        { category: "Rural Roads", lakh: 50 },
      ],
    },
    {
      mpName: "Shri Asaduddin Owaisi",
      annualCr: 5.0,
      usedCr: 4.70,
      breakdown: [
        { category: "Health & Sanitation", lakh: 195 },
        { category: "Education", lakh: 150 },
        { category: "Community Assets", lakh: 125 },
      ],
    },
    {
      mpName: "Shri M. Raghunandan Rao",
      annualCr: 5.0,
      usedCr: 3.80,
      breakdown: [
        { category: "Social Infrastructure", lakh: 160 },
        { category: "Rural Roads", lakh: 140 },
        { category: "Drinking Water", lakh: 80 },
      ],
    },
  ],
};