// AUTO-GENERATED from the official MoSPI allocation CSV — do not edit by hand.
// Regenerate with: backend/.venv/bin/python backend/scripts/generate_allocations_ts.py
// Source: “Allocated Limit for Hon'ble MPs” (all Lok Sabha MPs, FY 2025–26).
// `allocatedCr` is null where the portal row publishes no amount (pending revision).

export interface MpAllocationRow {
  mpName: string;
  state: string;
  constituency: string;
  allocatedCr: number | null;
}

export const MP_ALLOCATIONS: MpAllocationRow[] = [
  { mpName: 'AASHTIKAR PATIL NAGESH BAPURAO', state: 'Maharashtra', constituency: 'HINGOLI', allocatedCr: 19.03 },
  { mpName: 'ABDUL RASHID SHEIKH', state: 'Jammu And Kashmir', constituency: 'BARAMULLAH', allocatedCr: 15.48 },
  { mpName: 'ABHAY KUMAR SINHA', state: 'Bihar', constituency: 'AURANGABAD_BR', allocatedCr: 14.70 },
  { mpName: 'ABHIJIT GANGOPADHYAY', state: 'West Bengal', constituency: 'TAMLUK', allocatedCr: 14.70 },
  { mpName: 'Abu Taher Khan', state: 'West Bengal', constituency: 'MURSHIDABAD', allocatedCr: 14.70 },
  { mpName: 'ADHIKARI SOUMENDU', state: 'West Bengal', constituency: 'KANTHI', allocatedCr: 14.70 },
  { mpName: 'ADITYA YADAV', state: 'Uttar Pradesh', constituency: 'BADAUN', allocatedCr: 14.70 },
  { mpName: 'Adv Adoor Prakash', state: 'Kerala', constituency: 'ATTINGAL', allocatedCr: 15.13 },
  { mpName: 'Adv Dean Kuriakose', state: 'Kerala', constituency: 'IDUKKI', allocatedCr: 14.70 },
  { mpName: 'ADV GOWAAL KAGADA PADAVI', state: 'Maharashtra', constituency: 'NANDURBAR(ST)', allocatedCr: 14.78 },
  { mpName: 'ADV K FRANCIS GEORGE', state: 'Kerala', constituency: 'KOTTAYAM', allocatedCr: 18.87 },
  { mpName: 'AFZAL ANSARI', state: 'Uttar Pradesh', constituency: 'GHAZIPUR', allocatedCr: 22.05 },
  { mpName: 'AGA SYED RUHULLAH MEHDI', state: 'Jammu And Kashmir', constituency: 'SRINAGAR', allocatedCr: 14.70 },
  { mpName: 'Ajay Bhatt', state: 'Uttarakhand', constituency: 'NAINITAL UDHAM SINGH NAG.', allocatedCr: 14.70 },
  { mpName: 'Ajay Kumar Mandal', state: 'Bihar', constituency: 'BHAGALPUR', allocatedCr: 14.70 },
  { mpName: 'Ajay Tamta', state: 'Uttarakhand', constituency: 'ALMORA(SC)', allocatedCr: 14.70 },
  { mpName: 'AJENDRA SINGH LODHI', state: 'Uttar Pradesh', constituency: 'HAMIRPUR_UP', allocatedCr: 14.70 },
  { mpName: 'AKHILESH YADAV', state: 'Uttar Pradesh', constituency: 'KANNAUJ', allocatedCr: 14.70 },
  { mpName: 'AKSHAYA YADAV', state: 'Uttar Pradesh', constituency: 'FIROZABAD', allocatedCr: 14.70 },
  { mpName: 'ALFRED KANNGAM S ARTHUR', state: 'Manipur', constituency: 'OUTER MANIPUR(ST)', allocatedCr: 14.70 },
  { mpName: 'Alok Kumar Suman', state: 'Bihar', constituency: 'GOPALGANJ (SC)', allocatedCr: 14.70 },
  { mpName: 'ALOK SHARMA', state: 'Madhya Pradesh', constituency: 'BHOPAL', allocatedCr: 14.70 },
  { mpName: 'AMAR SHARADRAO KALE', state: 'Maharashtra', constituency: 'WARDHA', allocatedCr: 14.70 },
  { mpName: 'AMARSING TISSO', state: 'Assam', constituency: 'Diphu (ST)', allocatedCr: 14.70 },
  { mpName: 'AMBICA G LAKSHMINARAYANA VALMIKI', state: 'Andhra Pradesh', constituency: 'ANANTAPUR', allocatedCr: 20.19 },
  { mpName: 'Amol Ramsing Kolhe', state: 'Maharashtra', constituency: 'SHIRUR', allocatedCr: 14.70 },
  { mpName: 'AMRARAM', state: 'Rajasthan', constituency: 'SIKAR', allocatedCr: 16.57 },
  { mpName: 'AMRINDER SINGH RAJA WARRING', state: 'Punjab', constituency: 'LUDHIANA', allocatedCr: 14.70 },
  { mpName: 'ANAND BHADAURIYA', state: 'Uttar Pradesh', constituency: 'DHAURAHRA', allocatedCr: 14.70 },
  { mpName: 'ANAND KUMAR', state: 'Uttar Pradesh', constituency: 'BAHRAICH(SC)', allocatedCr: 14.70 },
  { mpName: 'ANANTA NAYAK', state: 'Odisha', constituency: 'KEONJHAR(ST)', allocatedCr: 14.70 },
  { mpName: 'Andimuthu Raja', state: 'Tamil Nadu', constituency: 'NILGIRIS(SC)', allocatedCr: 14.70 },
  { mpName: 'ANDREW J. SYNGKON', state: 'Meghalaya', constituency: 'SHILLONG', allocatedCr: 9.80 },
  { mpName: 'ANGOMCHA BIMOL AKOIJAM', state: 'Manipur', constituency: 'INNER MANIPUR', allocatedCr: 14.70 },
  { mpName: 'ANIL BALUNI', state: 'Uttarakhand', constituency: 'GARHWAL', allocatedCr: 14.70 },
  { mpName: 'ANIL YESHWANT DESAI', state: 'Maharashtra', constituency: 'MUMBAI SOUTH CENTRAL', allocatedCr: 14.70 },
  { mpName: 'ANITA NAGARSINGH CHOUHAN', state: 'Madhya Pradesh', constituency: 'RATLAM(ST)', allocatedCr: 14.70 },
  { mpName: 'ANITA SUBHADARSHINI', state: 'Odisha', constituency: 'ASKA', allocatedCr: 14.70 },
  { mpName: 'Annpurna Devi', state: 'Jharkhand', constituency: 'KODARMA', allocatedCr: 16.67 },
  { mpName: 'ANOOP PRADHAN BALMIKI', state: 'Uttar Pradesh', constituency: 'HATHRAS (SC)', allocatedCr: 14.70 },
  { mpName: 'Anto Antony', state: 'Kerala', constituency: 'PATHANAMTHITTA', allocatedCr: 14.70 },
  { mpName: 'ANUP SANJAY DHOTRE', state: 'Maharashtra', constituency: 'AKOLA', allocatedCr: 14.70 },
  { mpName: 'Anurag Sharma', state: 'Uttar Pradesh', constituency: 'JHANSI', allocatedCr: 14.70 },
  { mpName: 'Anurag Singh Thakur', state: 'Himachal Pradesh', constituency: 'HAMIRPUR_HP', allocatedCr: 14.96 },
  { mpName: 'Appalanaidu Kalisetti', state: 'Andhra Pradesh', constituency: 'VIZIANAGARAM', allocatedCr: 14.70 },
  { mpName: 'ARUN BHARTI', state: 'Bihar', constituency: 'JAMUI(SC)', allocatedCr: 19.49 },
  { mpName: 'ARUN GOVIL', state: 'Uttar Pradesh', constituency: 'MEERUT', allocatedCr: 14.70 },
  { mpName: 'ARUN NEHRU', state: 'Tamil Nadu', constituency: 'PERAMBALUR', allocatedCr: 14.70 },
  { mpName: 'ARUNA. D. K', state: 'Telangana', constituency: 'MAHABUBNAGAR', allocatedCr: 14.70 },
  { mpName: 'ARUP CHAKRABORTY', state: 'West Bengal', constituency: 'BANKURA', allocatedCr: 14.70 },
  { mpName: 'Arvind Dharmapuri', state: 'Telangana', constituency: 'NIZAMABAD', allocatedCr: 28.14 },
  { mpName: 'Arvind Ganpat Sawant', state: 'Maharashtra', constituency: 'MUMBAI SOUTH', allocatedCr: 14.70 },
  { mpName: 'Asaduddin Owaisi', state: 'Telangana', constituency: 'HYDERABAD', allocatedCr: 14.70 },
  { mpName: 'ASHISH DUBEY', state: 'Madhya Pradesh', constituency: 'JABALPUR', allocatedCr: 14.70 },
  { mpName: 'Ashok Kumar Rawat', state: 'Uttar Pradesh', constituency: 'MISRIKH(SC)', allocatedCr: 14.70 },
  { mpName: 'Ashok Kumar Yadav', state: 'Bihar', constituency: 'MADHUBANI', allocatedCr: 14.70 },
  { mpName: 'Asit Kumar Mal', state: 'West Bengal', constituency: 'BOLPUR(SC)', allocatedCr: 27.57 },
  { mpName: 'ATUL GARG', state: 'Uttar Pradesh', constituency: 'GHAZIABAD', allocatedCr: 15.53 },
  { mpName: 'AVIMANYU SETHI', state: 'Odisha', constituency: 'BHADRAK(SC)', allocatedCr: 14.70 },
  { mpName: 'AWADHESH PRASAD', state: 'Uttar Pradesh', constituency: 'FAIZABAD', allocatedCr: 14.70 },
  { mpName: 'AZAD KIRTI JHA', state: 'West Bengal', constituency: 'BARDHAMAN-DURGAPUR', allocatedCr: 17.97 },
  { mpName: 'B K PARTHASARATHI', state: 'Andhra Pradesh', constituency: 'HINDUPUR', allocatedCr: 16.05 },
  { mpName: 'BABU SINGH KUSHWAHA', state: 'Uttar Pradesh', constituency: 'JAUNPUR', allocatedCr: 14.70 },
  { mpName: 'BACHHAV SHOBHA DINESH', state: 'Maharashtra', constituency: 'DHULE', allocatedCr: 14.70 },
  { mpName: 'BAG MITALI', state: 'West Bengal', constituency: 'ARAMBAG(SC)', allocatedCr: 14.70 },
  { mpName: 'BAIJAYANT PANDA', state: 'Odisha', constituency: 'KENDRAPARA', allocatedCr: 14.70 },
  { mpName: 'BAJRANG MANOHAR SONWANE', state: 'Maharashtra', constituency: 'BEED', allocatedCr: 16.59 },
  { mpName: 'BALABHADRA MAJHI', state: 'Odisha', constituency: 'NABARANGPUR(ST)', allocatedCr: 14.74 },
  { mpName: 'Balashowry Vallabbhaneni', state: 'Andhra Pradesh', constituency: 'MACHILIPATNAM', allocatedCr: 14.70 },
  { mpName: 'BALRAM NAIK PORIKA', state: 'Telangana', constituency: 'MAHABUBABAD', allocatedCr: 14.70 },
  { mpName: 'BALWANT BASWANT WANKHADE', state: 'Maharashtra', constituency: 'AMRAVATI(SC)', allocatedCr: 19.83 },
  { mpName: 'BALYA MAMA SURESH GOPINATH MHATRE', state: 'Maharashtra', constituency: 'BHIWANDI', allocatedCr: 14.70 },
  { mpName: 'Bansuri Swaraj', state: 'Delhi', constituency: 'NEW DELHI', allocatedCr: 15.43 },
  { mpName: 'BAPI HALDAR', state: 'West Bengal', constituency: 'MATHURAPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'BASAVARAJ BOMMAI', state: 'Karnataka', constituency: 'HAVERI', allocatedCr: 14.70 },
  { mpName: 'BASTIPATI NAGARAJU PANCHALINGALA', state: 'Andhra Pradesh', constituency: 'KURNOOL', allocatedCr: 16.00 },
  { mpName: 'Bhagirath Chaudhary', state: 'Rajasthan', constituency: 'AJMER', allocatedCr: 14.70 },
  { mpName: 'BHAJAN LAL JATAV', state: 'Rajasthan', constituency: 'KARAULI-DHOLPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'BHARAT SINGH KUSHWAH', state: 'Madhya Pradesh', constituency: 'GWALIOR', allocatedCr: 15.15 },
  { mpName: 'BHARATBHAI MANUBHAI SUTARIYA', state: 'Gujarat', constituency: 'AMRELI', allocatedCr: 14.70 },
  { mpName: 'Bharatsinhji Shankarji Dabhi', state: 'Gujarat', constituency: 'PATAN', allocatedCr: 14.70 },
  { mpName: 'BHARTI PARDHI', state: 'Madhya Pradesh', constituency: 'BALAGHAT', allocatedCr: 15.44 },
  { mpName: 'BHASKAR MURLIDHAR BHAGARE', state: 'Maharashtra', constituency: 'DINDORI(ST)', allocatedCr: 14.70 },
  { mpName: 'BHAUSAHEB RAJARAM WAKCHAURE', state: 'Maharashtra', constituency: 'SHIRDI(SC)', allocatedCr: 14.70 },
  { mpName: 'BHOJRAJ NAG', state: 'Chhattisgarh', constituency: 'KANKER(ST)', allocatedCr: 16.47 },
  { mpName: 'Bhola Singh', state: 'Uttar Pradesh', constituency: 'BULANDSHAHR(SC)', allocatedCr: 14.70 },
  { mpName: 'BHUMARE SANDIPANRAO ASARAM', state: 'Maharashtra', constituency: 'AURANGABAD_MH', allocatedCr: 14.70 },
  { mpName: 'Bhupathiraju Srinivasa varma', state: 'Andhra Pradesh', constituency: 'NARASAPURAM', allocatedCr: 14.70 },
  { mpName: 'BHUPENDER YADAV', state: 'Rajasthan', constituency: 'ALWAR', allocatedCr: 14.70 },
  { mpName: 'BIBHU PRASAD TARAI', state: 'Odisha', constituency: 'JAGATSINGHPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Bidyut Baran Mahato', state: 'Jharkhand', constituency: 'JAMSHEDPUR', allocatedCr: 14.70 },
  { mpName: 'BIJULI KALITA MEDHI', state: 'Assam', constituency: 'GUWAHATI', allocatedCr: 14.70 },
  { mpName: 'BIPLAB KUMAR DEB', state: 'Tripura', constituency: 'TRIPURA WEST', allocatedCr: 14.70 },
  { mpName: 'BISHNU PADA RAY', state: 'Andaman And Nicobar Islands', constituency: 'ANDAMAN AND NICOBAR ISLANDS', allocatedCr: 14.70 },
  { mpName: 'BRIJENDRA SINGH OLA', state: 'Rajasthan', constituency: 'JHUNJHUNU', allocatedCr: 14.70 },
  { mpName: 'BRIJMOHAN AGRAWAL', state: 'Chhattisgarh', constituency: 'RAIPUR', allocatedCr: 15.38 },
  { mpName: 'BUNTY VIVEK SAHU', state: 'Madhya Pradesh', constituency: 'CHHINDWARA', allocatedCr: 14.70 },
  { mpName: 'C R Patil', state: 'Gujarat', constituency: 'NAVSARI', allocatedCr: 15.85 },
  { mpName: 'C.M.RAMESH', state: 'Andhra Pradesh', constituency: 'ANAKAPALLE', allocatedCr: 20.25 },
  { mpName: 'CAPTAIN BRIJESH CHOWTA', state: 'Karnataka', constituency: 'DAKSHINA KANNADA', allocatedCr: 14.70 },
  { mpName: 'CAPTAIN VIRIATO FERNANDES', state: 'Goa', constituency: 'SOUTH GOA', allocatedCr: 14.70 },
  { mpName: 'CHAMALA KIRAN KUMAR REDDY', state: 'Telangana', constituency: 'BHONGIR', allocatedCr: 14.70 },
  { mpName: 'CHANDAN CHAUHAN', state: 'Uttar Pradesh', constituency: 'BIJNOR', allocatedCr: 14.70 },
  { mpName: 'Chandra Prakash Joshi', state: 'Rajasthan', constituency: 'CHITTORGARH', allocatedCr: 14.70 },
  { mpName: 'CHANDRA SHEKHAR', state: 'Uttar Pradesh', constituency: 'NAGINA(SC)', allocatedCr: 14.70 },
  { mpName: 'CHANDUBHAI CHHAGANBHAI SHIHORA', state: 'Gujarat', constituency: 'SURENDRANAGAR', allocatedCr: 14.70 },
  { mpName: 'CHARANJIT SINGH CHANNI', state: 'Punjab', constituency: 'JALANDHAR(SC)', allocatedCr: 14.70 },
  { mpName: 'CHAVAN VASANTRAO BALWANTRAO', state: 'Maharashtra', constituency: 'NANDED', allocatedCr: null },
  { mpName: 'CHHATRA PAL SINGH GANGWAR', state: 'Uttar Pradesh', constituency: 'BAREILLY', allocatedCr: 14.70 },
  { mpName: 'CHHATRAPATI SHAHU SHAHAJI', state: 'Maharashtra', constituency: 'KOLHAPUR', allocatedCr: 14.70 },
  { mpName: 'CHHOTELAL', state: 'Uttar Pradesh', constituency: 'ROBERTSGANJ(SC)', allocatedCr: 14.70 },
  { mpName: 'CHINTAMANI MAHARAJ', state: 'Chhattisgarh', constituency: 'SARGUJA(ST)', allocatedCr: 14.70 },
  { mpName: 'CHIRAG PASWAN', state: 'Bihar', constituency: 'HAJIPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'CN Annadurai', state: 'Tamil Nadu', constituency: 'TIRUVANNAMALAI', allocatedCr: 14.86 },
  { mpName: 'D M Kathir Anand', state: 'Tamil Nadu', constituency: 'VELLORE', allocatedCr: 16.02 },
  { mpName: 'D Ravikumar', state: 'Tamil Nadu', constituency: 'VILUPPURAM(SC)', allocatedCr: 19.76 },
  { mpName: 'Daggubati Purandeshwari', state: 'Andhra Pradesh', constituency: 'RAJAHMUNDRY', allocatedCr: 14.70 },
  { mpName: 'DAGGUMALLA PRASADA RAO', state: 'Andhra Pradesh', constituency: 'CHITTOOR', allocatedCr: 14.70 },
  { mpName: 'DAMODAR AGARWAL', state: 'Rajasthan', constituency: 'BHILWARA', allocatedCr: 14.70 },
  { mpName: 'DAROGA PRASAD SAROJ', state: 'Uttar Pradesh', constituency: 'LALGANJ (SC)', allocatedCr: 14.70 },
  { mpName: 'DARSHAN SINGH CHOUDHARY', state: 'Madhya Pradesh', constituency: 'HOSHANGABAD', allocatedCr: 14.70 },
  { mpName: 'DEEPENDER SINGH HOODA', state: 'Haryana', constituency: 'ROHTAK', allocatedCr: 14.70 },
  { mpName: 'Devendra Alias Bhole Singh', state: 'Uttar Pradesh', constituency: 'AKBARPUR', allocatedCr: 14.70 },
  { mpName: 'DEVESH CHANDRA THAKUR', state: 'Bihar', constituency: 'SITAMARHI', allocatedCr: 16.38 },
  { mpName: 'DEVESH SHAKYA', state: 'Uttar Pradesh', constituency: 'ETAH', allocatedCr: 14.70 },
  { mpName: 'Devusinh Jesingbhai Chauhan', state: 'Gujarat', constituency: 'KHEDA', allocatedCr: 14.70 },
  { mpName: 'Dhairyasheel Sambhajirao Mane', state: 'Maharashtra', constituency: 'HATKANANGLE', allocatedCr: 14.70 },
  { mpName: 'DHANORKAR PRATIBHA SURESH ALIAS BALUBHAU', state: 'Maharashtra', constituency: 'CHANDRAPUR', allocatedCr: 14.70 },
  { mpName: 'DHARMENDRA PRADHAN', state: 'Odisha', constituency: 'SAMBALPUR', allocatedCr: 14.70 },
  { mpName: 'DHARMENDRA YADAV', state: 'Uttar Pradesh', constituency: 'AZAMGARH', allocatedCr: 14.70 },
  { mpName: 'DHAVAL LAXMANBHAI PATEL', state: 'Gujarat', constituency: 'VALSAD(ST)', allocatedCr: 14.70 },
  { mpName: 'Dileshwar Kamait', state: 'Bihar', constituency: 'SUPAUL', allocatedCr: 15.05 },
  { mpName: 'Dilip Saikia', state: 'Assam', constituency: 'Darrang-Udalguri', allocatedCr: 14.70 },
  { mpName: 'Dinesh Chandra Yadav', state: 'Bihar', constituency: 'MADHEPURA', allocatedCr: 15.01 },
  { mpName: 'DINESHBHAI MAKWANA', state: 'Gujarat', constituency: 'AHMEDABAD WEST(SC)', allocatedCr: 16.04 },
  { mpName: 'DR BYREDDY SHABARI', state: 'Andhra Pradesh', constituency: 'NANDYAL', allocatedCr: 18.26 },
  { mpName: 'DR C N MANJUNATH', state: 'Karnataka', constituency: 'BANGALORE RURAL', allocatedCr: 14.70 },
  { mpName: 'Dr Chandra Sekhar Pemmasani', state: 'Andhra Pradesh', constituency: 'GUNTUR', allocatedCr: 15.98 },
  { mpName: 'DR DHARAMVIRA GANDHI', state: 'Punjab', constituency: 'PATIALA', allocatedCr: 14.70 },
  { mpName: 'Dr Jayanta Kumar Roy', state: 'West Bengal', constituency: 'JALPAIGURI(SC)', allocatedCr: 14.70 },
  { mpName: 'DR KALGE SHIVAJI BANDAPPA', state: 'Maharashtra', constituency: 'LATUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Dr Mohammad Jawed', state: 'Bihar', constituency: 'KISHANGANJ', allocatedCr: 14.87 },
  { mpName: 'DR RAJKUMAR SANGWAN', state: 'Uttar Pradesh', constituency: 'BAGHPAT', allocatedCr: 14.70 },
  { mpName: 'DR RANI SRI KUMAR', state: 'Tamil Nadu', constituency: 'TENKASI(SC)', allocatedCr: 15.31 },
  { mpName: 'Dr Shashi Tharoor', state: 'Kerala', constituency: 'THIRUVANANTHAPURAM', allocatedCr: 14.70 },
  { mpName: 'Dr Sukanta Majumdar', state: 'West Bengal', constituency: 'BALURGHAT', allocatedCr: 15.71 },
  { mpName: 'DR. HEMANG JOSHI', state: 'Gujarat', constituency: 'VADODARA', allocatedCr: 14.70 },
  { mpName: 'DR. HEMANT VISHNU SAVARA', state: 'Maharashtra', constituency: 'PALGHAR(ST)', allocatedCr: 14.70 },
  { mpName: 'DR. KIRSAN NAMDEO', state: 'Maharashtra', constituency: 'GADCHIROLI-CHIMUR(ST)', allocatedCr: 14.70 },
  { mpName: 'DR. LATA WANKHEDE', state: 'Madhya Pradesh', constituency: 'SAGAR', allocatedCr: 14.70 },
  { mpName: 'DR. M.P ABDUSSAMAD SAMADANI', state: 'Kerala', constituency: 'PONNANI', allocatedCr: 17.04 },
  { mpName: 'DR. MANSUKH MANDAVIYA', state: 'Gujarat', constituency: 'PORBANDAR', allocatedCr: 14.70 },
  { mpName: 'DR. PRABHA MALLIKARJUN', state: 'Karnataka', constituency: 'DAVANAGERE', allocatedCr: 15.02 },
  { mpName: 'DR. PRADEEP KUMAR PANIGRAHY', state: 'Odisha', constituency: 'BERHAMPUR', allocatedCr: 14.70 },
  { mpName: 'DR. PRASHANT YADAORAO PADOLE', state: 'Maharashtra', constituency: 'BHANDARA-GONDIYA', allocatedCr: 15.97 },
  { mpName: 'DR. RAJ KUMAR CHABBEWAL', state: 'Punjab', constituency: 'HOSHIARPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'DR. RAJESH MISHRA', state: 'Madhya Pradesh', constituency: 'SIDHI', allocatedCr: 26.27 },
  { mpName: 'DR. S P SINGH', state: 'Uttar Pradesh', constituency: 'PRATAPGARH', allocatedCr: 14.70 },
  { mpName: 'DR. SHARMILA SARKAR', state: 'West Bengal', constituency: 'BARDHAMAN PURBA(SC)', allocatedCr: 14.70 },
  { mpName: 'DR.K.SUDHAKAR', state: 'Karnataka', constituency: 'CHIKBALLAPUR', allocatedCr: 14.71 },
  { mpName: 'DR.MALLU RAVI', state: 'Telangana', constituency: 'NAGARKURNOOL(SC)', allocatedCr: 14.70 },
  { mpName: 'DULU MAHATO', state: 'Jharkhand', constituency: 'DHANBAD', allocatedCr: 14.70 },
  { mpName: 'DURAI VAIKO', state: 'Tamil Nadu', constituency: 'TIRUCHIRAPPALLI', allocatedCr: 14.70 },
  { mpName: 'Durga Das Uikey', state: 'Madhya Pradesh', constituency: 'BETUL(ST)', allocatedCr: 15.16 },
  { mpName: 'Dushyant Singh', state: 'Rajasthan', constituency: 'JHALAWAR-BARAN', allocatedCr: 14.70 },
  { mpName: 'E. TUKARAM', state: 'Karnataka', constituency: 'BELLARY(ST)', allocatedCr: 14.70 },
  { mpName: 'E.T. MOHAMMED BASHEER', state: 'Kerala', constituency: 'MALAPPURAM', allocatedCr: 16.39 },
  { mpName: 'EATALA RAJENDER', state: 'Telangana', constituency: 'MALKAJGIRI', allocatedCr: 32.75 },
  { mpName: 'ESWARASAMY K', state: 'Tamil Nadu', constituency: 'POLLACHI', allocatedCr: 16.23 },
  { mpName: 'Faggan Singh Kulaste', state: 'Madhya Pradesh', constituency: 'MANDLA(ST)', allocatedCr: 15.19 },
  { mpName: 'G. KUMAR NAIK', state: 'Karnataka', constituency: 'RAICHUR(ST)', allocatedCr: 14.71 },
  { mpName: 'GAIKWAD VARSHA EKNATH', state: 'Maharashtra', constituency: 'MUMBAI NORTH-CENTRAL', allocatedCr: 14.70 },
  { mpName: 'Gajendra Singh Patel', state: 'Madhya Pradesh', constituency: 'KHARGONE(ST)', allocatedCr: 14.70 },
  { mpName: 'Gajendra Singh Shekhawat', state: 'Rajasthan', constituency: 'JODHPUR', allocatedCr: 14.70 },
  { mpName: 'GANAPATHY RAJKUMAR P', state: 'Tamil Nadu', constituency: 'COIMBATORE', allocatedCr: 14.74 },
  { mpName: 'Ganesan Selvam', state: 'Tamil Nadu', constituency: 'KANCHEEPURAM(SC)', allocatedCr: 18.65 },
  { mpName: 'Ganesh Singh', state: 'Madhya Pradesh', constituency: 'SATNA', allocatedCr: 14.70 },
  { mpName: 'GAURAV GOGOI', state: 'Assam', constituency: 'JORHAT', allocatedCr: 14.70 },
  { mpName: 'GENIBEN NAGAJI THAKOR', state: 'Gujarat', constituency: 'BANASKANTHA', allocatedCr: 14.70 },
  { mpName: 'Giridhari Yadav', state: 'Bihar', constituency: 'BANKA', allocatedCr: 14.70 },
  { mpName: 'Giriraj Singh', state: 'Bihar', constituency: 'BEGUSARAI', allocatedCr: 14.70 },
  { mpName: 'GM Harish Balayogi', state: 'Andhra Pradesh', constituency: 'AMALAPURAM(SC)', allocatedCr: 14.70 },
  { mpName: 'GODAM NAGESH', state: 'Telangana', constituency: 'ADILABAD(ST)', allocatedCr: 14.70 },
  { mpName: 'GOPINATH K', state: 'Tamil Nadu', constituency: 'KRISHNAGIRI', allocatedCr: 14.70 },
  { mpName: 'GOVIND MAKTHAPPA KARJOL', state: 'Karnataka', constituency: 'CHITRADURGA(SC)', allocatedCr: 17.73 },
  { mpName: 'Gumma Thanuja Rani', state: 'Andhra Pradesh', constituency: 'ARAKU(ST)', allocatedCr: 14.95 },
  { mpName: 'GURMEET SINGH MEET HAYER', state: 'Punjab', constituency: 'SANGRUR', allocatedCr: 14.70 },
  { mpName: 'Gyaneshwar Patil', state: 'Madhya Pradesh', constituency: 'KHANDWA', allocatedCr: 15.57 },
  { mpName: 'H.D. KUMARASWAMY', state: 'Karnataka', constituency: 'MANDYA', allocatedCr: 14.70 },
  { mpName: 'HARENDRA SINGH MALIK', state: 'Uttar Pradesh', constituency: 'MUZAFFARNAGAR', allocatedCr: 14.70 },
  { mpName: 'HARIBHAI PATEL', state: 'Gujarat', constituency: 'MAHESANA', allocatedCr: 14.70 },
  { mpName: 'HARISH CHANDRA MEENA', state: 'Rajasthan', constituency: 'TONK-SAWAI MADHOPUR', allocatedCr: 14.70 },
  { mpName: 'Harsh Malhotra', state: 'Delhi', constituency: 'EAST DELHI', allocatedCr: 14.71 },
  { mpName: 'Hasmukh Bhai Soma Bhai Patel', state: 'Gujarat', constituency: 'AHMEDABAD EAST', allocatedCr: 14.70 },
  { mpName: 'IMRAN MASOOD', state: 'Uttar Pradesh', constituency: 'SAHARANPUR', allocatedCr: 14.70 },
  { mpName: 'Indra Hang Subba', state: 'Sikkim', constituency: 'SIKKIM', allocatedCr: 15.20 },
  { mpName: 'IQRA CHOUDHARY', state: 'Uttar Pradesh', constituency: 'KAIRANA', allocatedCr: 14.70 },
  { mpName: 'ISHA KHAN CHOUDHURY', state: 'West Bengal', constituency: 'MALDAHA DAKSHIN', allocatedCr: 14.70 },
  { mpName: 'JAGADISH CHANDRA BARMA BASUNIA', state: 'West Bengal', constituency: 'COOCHBEHAR(SC)', allocatedCr: 16.86 },
  { mpName: 'JAGADISH SHETTAR', state: 'Karnataka', constituency: 'BELGAUM', allocatedCr: 14.70 },
  { mpName: 'Jagannath Sarkar', state: 'West Bengal', constituency: 'RANAGHAT(SC)', allocatedCr: 14.70 },
  { mpName: 'Jagdambika Pal', state: 'Uttar Pradesh', constituency: 'DOMARIYAGANJ', allocatedCr: 16.06 },
  { mpName: 'JAI PARKASH', state: 'Haryana', constituency: 'HISAR', allocatedCr: 14.70 },
  { mpName: 'Jai Prakash', state: 'Uttar Pradesh', constituency: 'HARDOI (SC)', allocatedCr: 14.70 },
  { mpName: 'Janardan Mishra', state: 'Madhya Pradesh', constituency: 'REWA', allocatedCr: 14.70 },
  { mpName: 'JASHUBHAI BHILUBHAI RATHVA', state: 'Gujarat', constituency: 'CHHOTA UDAIPUR(ST)', allocatedCr: 14.70 },
  { mpName: 'Jaswantsinh Sumanbhai Bhabhor', state: 'Gujarat', constituency: 'DAHOD(ST)', allocatedCr: 14.70 },
  { mpName: 'JITAN RAM MANJHI', state: 'Bihar', constituency: 'GAYA (SC)', allocatedCr: 14.70 },
  { mpName: 'JITENDRA KUMAR DOHARE', state: 'Uttar Pradesh', constituency: 'ETAWAH(SC)', allocatedCr: 18.87 },
  { mpName: 'Jitendra Singh', state: 'Jammu And Kashmir', constituency: 'UDHAMPUR', allocatedCr: 14.70 },
  { mpName: 'JITIN PRASADA', state: 'Uttar Pradesh', constituency: 'PILIBHIT', allocatedCr: 14.70 },
  { mpName: 'JOBA MAJHI', state: 'Jharkhand', constituency: 'SINGHBHUM(ST)', allocatedCr: 14.70 },
  { mpName: 'JOYANTA BASUMATARY', state: 'Assam', constituency: 'KOKRAJHAR (ST)', allocatedCr: 14.70 },
  { mpName: 'JUNE MALIAH', state: 'West Bengal', constituency: 'MEDINIPUR', allocatedCr: 14.70 },
  { mpName: 'JYOTIRADITYA M. SCINDIA', state: 'Madhya Pradesh', constituency: 'GUNA', allocatedCr: 14.70 },
  { mpName: 'Jyotsna Charandas Mahant', state: 'Chhattisgarh', constituency: 'KORBA', allocatedCr: 15.52 },
  { mpName: 'K E PRAKASH', state: 'Tamil Nadu', constituency: 'ERODE', allocatedCr: 14.70 },
  { mpName: 'K RADHAKRISHNAN', state: 'Kerala', constituency: 'ALATHUR(SC)', allocatedCr: 14.70 },
  { mpName: 'K Subbarayan', state: 'Tamil Nadu', constituency: 'TIRUPPUR', allocatedCr: 14.70 },
  { mpName: 'K. C VENUGOPAL', state: 'Kerala', constituency: 'ALAPPUZHA', allocatedCr: 14.70 },
  { mpName: 'K. RAJASHEKAR BASAVARAJ HITNAL', state: 'Karnataka', constituency: 'KOPPAL', allocatedCr: 14.70 },
  { mpName: 'KADIYAM KAVYA', state: 'Telangana', constituency: 'WARANGEL(SC)', allocatedCr: 14.70 },
  { mpName: 'Kakoli Ghosh Dastidar', state: 'West Bengal', constituency: 'BARASAT', allocatedCr: 14.70 },
  { mpName: 'Kalaben Mohanbhai Delkar', state: 'The Dadra And Nagar Haveli And Daman And Diu', constituency: 'DADRA & NAGAR HAVELI (ST)', allocatedCr: 26.95 },
  { mpName: 'Kalanidhi Veeraswamy', state: 'Tamil Nadu', constituency: 'CHENNAI NORTH', allocatedCr: 17.15 },
  { mpName: 'KALI CHARAN MUNDA', state: 'Jharkhand', constituency: 'KHUNTI(ST)', allocatedCr: 14.70 },
  { mpName: 'KALI CHARAN SINGH', state: 'Jharkhand', constituency: 'CHATRA', allocatedCr: 14.70 },
  { mpName: 'KALIPADA SAREN', state: 'West Bengal', constituency: 'JHARGRAM(ST)', allocatedCr: 14.70 },
  { mpName: 'Kalyan Banerjee', state: 'West Bengal', constituency: 'SREERAMPUR', allocatedCr: 14.70 },
  { mpName: 'KALYAN VAIJINATHRAO KALE', state: 'Maharashtra', constituency: 'JALNA', allocatedCr: 14.70 },
  { mpName: 'KAMAKHYA PRASAD TASA', state: 'Assam', constituency: 'Kaziranga', allocatedCr: 14.70 },
  { mpName: 'Kamaljeet Sehrawat', state: 'Delhi', constituency: 'WEST DELHI', allocatedCr: 14.70 },
  { mpName: 'KAMLESH JANGDE', state: 'Chhattisgarh', constituency: 'JANJGIR CHAMPA(SC)', allocatedCr: 15.04 },
  { mpName: 'Kamlesh Paswan', state: 'Uttar Pradesh', constituency: 'BANSGAON(SC)', allocatedCr: 14.70 },
  { mpName: 'Kangana Ranaut', state: 'Himachal Pradesh', constituency: 'MANDI', allocatedCr: 14.70 },
  { mpName: 'Kani K Navas', state: 'Tamil Nadu', constituency: 'RAMANATHAPURAM', allocatedCr: 14.70 },
  { mpName: 'Kanimozhi Karunanidhi', state: 'Tamil Nadu', constituency: 'THOOTHUKKUDI', allocatedCr: 14.70 },
  { mpName: 'KANWAR SINGH TANWAR', state: 'Uttar Pradesh', constituency: 'AMROHA', allocatedCr: 14.70 },
  { mpName: 'KARAN BHUSHAN SINGH', state: 'Uttar Pradesh', constituency: 'KAISERGANJ', allocatedCr: 14.70 },
  { mpName: 'KARTICK CHANDRA PAUL', state: 'West Bengal', constituency: 'RAIGANJ', allocatedCr: 20.27 },
  { mpName: 'Kaushalendra Kumar', state: 'Bihar', constituency: 'NALANDA', allocatedCr: 14.70 },
  { mpName: 'Khagen Murmu', state: 'West Bengal', constituency: 'MALDAHA UTTAR', allocatedCr: 14.70 },
  { mpName: 'Khalilur Rahaman', state: 'West Bengal', constituency: 'JANGIPUR', allocatedCr: 14.70 },
  { mpName: 'Kinjarapu Ram Mohan Naidu', state: 'Andhra Pradesh', constituency: 'SRIKAKULAM', allocatedCr: 17.12 },
  { mpName: 'Kiren Rijiju', state: 'Arunachal Pradesh', constituency: 'ARUNACHAL WEST', allocatedCr: 14.70 },
  { mpName: 'Kirti Vardhan Singh', state: 'Uttar Pradesh', constituency: 'GONDA', allocatedCr: 14.70 },
  { mpName: 'Kishan Reddy Gangapuram', state: 'Telangana', constituency: 'SECUNDERABAD', allocatedCr: 14.70 },
  { mpName: 'KISHORI LAL', state: 'Uttar Pradesh', constituency: 'AMETHI', allocatedCr: 17.15 },
  { mpName: 'KONDA VISHWESHWAR REDDY', state: 'Telangana', constituency: 'CHELVELLA', allocatedCr: 23.37 },
  { mpName: 'KOTA SRINIVAS POOJARY', state: 'Karnataka', constituency: 'UDUPI CHIKMAGALUR', allocatedCr: 15.11 },
  { mpName: 'Kripanath Mallah', state: 'Assam', constituency: 'KARIMGANJ (SC)', allocatedCr: 14.70 },
  { mpName: 'Krishan Pal Gurjar', state: 'Haryana', constituency: 'FARIDABAD', allocatedCr: 14.70 },
  { mpName: 'KRISHNA DEVI SHIVSHANKER PATEL', state: 'Uttar Pradesh', constituency: 'BANDA', allocatedCr: 14.70 },
  { mpName: 'Krishna Prasad Tenneti', state: 'Andhra Pradesh', constituency: 'BAPATLA', allocatedCr: 16.78 },
  { mpName: 'KRITI DEVI DEBBARMAN', state: 'Tripura', constituency: 'TRIPURA EAST(ST)', allocatedCr: 14.70 },
  { mpName: 'KULDEEP INDORA', state: 'Rajasthan', constituency: 'GANGANAGAR(SC)', allocatedCr: 14.70 },
  { mpName: 'KUNDURU RAGHUVEER', state: 'Telangana', constituency: 'NALGONDA', allocatedCr: 16.30 },
  { mpName: 'LALJI VERMA', state: 'Uttar Pradesh', constituency: 'AMBEDKAR NAGAR', allocatedCr: 14.70 },
  { mpName: 'Lavu Sri Krishna Devarayalu', state: 'Andhra Pradesh', constituency: 'NARASARAOPET', allocatedCr: 17.40 },
  { mpName: 'LAXMIKANT PAPPU NISHAD', state: 'Uttar Pradesh', constituency: 'SANT KABIR NAGAR', allocatedCr: 14.70 },
  { mpName: 'LOVELY ANAND', state: 'Bihar', constituency: 'SHEOHAR', allocatedCr: 14.70 },
  { mpName: 'LUMBARAM', state: 'Rajasthan', constituency: 'JALORE', allocatedCr: 14.70 },
  { mpName: 'M. MALLESH BABU', state: 'Karnataka', constituency: 'KOLAR(SC)', allocatedCr: 14.71 },
  { mpName: 'M.K. VISHNUPRASAD', state: 'Tamil Nadu', constituency: 'CUDDALORE', allocatedCr: 14.70 },
  { mpName: 'Maddila Gurumoorthy', state: 'Andhra Pradesh', constituency: 'TIRUPATI(SC)', allocatedCr: 18.04 },
  { mpName: 'MADHAVANENI RAGHUNANDAN RAO', state: 'Telangana', constituency: 'MEDAK', allocatedCr: 14.70 },
  { mpName: 'Magunta Sreenivasulu Reddy', state: 'Andhra Pradesh', constituency: 'ONGOLE', allocatedCr: 14.70 },
  { mpName: 'Mahendra Singh Solanky', state: 'Madhya Pradesh', constituency: 'DEWAS(SC)', allocatedCr: 14.70 },
  { mpName: 'MAHESH KASHYAP', state: 'Chhattisgarh', constituency: 'BASTAR(ST)', allocatedCr: 14.70 },
  { mpName: 'Mahesh Sharma', state: 'Uttar Pradesh', constituency: 'GAUTAM BUDDHA NAGAR', allocatedCr: 14.88 },
  { mpName: 'MAHIMA KUMARI MEWAR', state: 'Rajasthan', constituency: 'RAJSAMAND', allocatedCr: 18.39 },
  { mpName: 'Mala Rajya Laxmi Shah', state: 'Uttarakhand', constituency: 'TEHRI GARHWAL', allocatedCr: 14.70 },
  { mpName: 'Mala Roy', state: 'West Bengal', constituency: 'KOLKATA DAKSHIN', allocatedCr: 14.70 },
  { mpName: 'MALAIYARASAN D', state: 'Tamil Nadu', constituency: 'KALLAKURICHI', allocatedCr: 20.16 },
  { mpName: 'MALVIKA DEVI', state: 'Odisha', constituency: 'KALAHANDI', allocatedCr: 14.70 },
  { mpName: 'MALVINDER SINGH KANG', state: 'Punjab', constituency: 'ANANDPUR SAHIB', allocatedCr: 14.70 },
  { mpName: 'MANI. A.', state: 'Tamil Nadu', constituency: 'DHARAMAPURI', allocatedCr: 16.45 },
  { mpName: 'Manickam Tagore B', state: 'Tamil Nadu', constituency: 'VIRUDHUNAGAR', allocatedCr: 14.70 },
  { mpName: 'MANISH JAISWAL', state: 'Jharkhand', constituency: 'HAZARIBAGH', allocatedCr: 14.70 },
  { mpName: 'MANISH TEWARI', state: 'Chandigarh', constituency: 'CHANDIGARH', allocatedCr: 17.84 },
  { mpName: 'MANJU SHARMA', state: 'Rajasthan', constituency: 'JAIPUR', allocatedCr: 16.71 },
  { mpName: 'MANNA LAL RAWAT', state: 'Rajasthan', constituency: 'UDAIPUR(ST)', allocatedCr: 14.70 },
  { mpName: 'MANOHAR LAL', state: 'Haryana', constituency: 'KARNAL', allocatedCr: 14.70 },
  { mpName: 'MANOJ KUMAR', state: 'Bihar', constituency: 'SASARAM(SC)', allocatedCr: 14.70 },
  { mpName: 'MANOJ TIGGA', state: 'West Bengal', constituency: 'ALIPURDUARS(ST)', allocatedCr: 14.70 },
  { mpName: 'Manoj Tiwari', state: 'Delhi', constituency: 'NORTH EAST DELHI', allocatedCr: 22.58 },
  { mpName: 'Mansukhbhai Dhanjibhai Vasava', state: 'Gujarat', constituency: 'BHARUCH', allocatedCr: 14.70 },
  { mpName: 'MIAN ALTAF AHMAD', state: 'Jammu And Kashmir', constituency: 'ANANTNAG', allocatedCr: 14.70 },
  { mpName: 'Midhun Reddy', state: 'Andhra Pradesh', constituency: 'RAJAMPET', allocatedCr: 17.90 },
  { mpName: 'MISHA BHARTI', state: 'Bihar', constituency: 'PATALIPUTRA', allocatedCr: 14.70 },
  { mpName: 'Mitesh Rameshbhai Bakabhai Patel', state: 'Gujarat', constituency: 'ANAND', allocatedCr: 14.70 },
  { mpName: 'Mohamed Haneefa', state: 'Ladakh', constituency: 'LADAKH', allocatedCr: 16.11 },
  { mpName: 'MOHIBBULLAH', state: 'Uttar Pradesh', constituency: 'RAMPUR', allocatedCr: 14.70 },
  { mpName: 'MOHITE PATIL DHAIRYASHEEL RAJSINH', state: 'Maharashtra', constituency: 'MADHA', allocatedCr: 19.56 },
  { mpName: 'Mr Gopal Jee Thakur', state: 'Bihar', constituency: 'DARBHANGA', allocatedCr: 14.70 },
  { mpName: 'Ms Mahua Moitra', state: 'West Bengal', constituency: 'KRISHNANAGAR', allocatedCr: 15.99 },
  { mpName: 'MUHAMMED HAMDULLAH SAYEED', state: 'Lakshadweep', constituency: 'LAKSHADWEEP(ST)', allocatedCr: 15.39 },
  { mpName: 'Mukesh Rajput', state: 'Uttar Pradesh', constituency: 'FARRUKHABAD', allocatedCr: 14.70 },
  { mpName: 'MUKESHKUMAR CHANDRAKAANT DALAL', state: 'Gujarat', constituency: 'SURAT', allocatedCr: 14.70 },
  { mpName: 'MURARI LAL MEENA', state: 'Rajasthan', constituency: 'DAUSA(ST)', allocatedCr: 14.70 },
  { mpName: 'MURASOLI S', state: 'Tamil Nadu', constituency: 'THANJAVUR', allocatedCr: 14.70 },
  { mpName: 'MURLIDHAR MOHOL', state: 'Maharashtra', constituency: 'PUNE', allocatedCr: 14.70 },
  { mpName: 'NABA CHARAN MAJHI', state: 'Odisha', constituency: 'MAYURBHANJ (ST)', allocatedCr: 14.76 },
  { mpName: 'NALIN SOREN', state: 'Jharkhand', constituency: 'DUMKA(ST)', allocatedCr: 14.74 },
  { mpName: 'NARAYAN DAS AHIRWAR', state: 'Uttar Pradesh', constituency: 'JALAUN(SC)', allocatedCr: 14.70 },
  { mpName: 'NARAYAN TATU RANE', state: 'Maharashtra', constituency: 'RATNAGIRI-SINDHUDURG', allocatedCr: 14.70 },
  { mpName: 'NARESH CHANDRA UTTAM PATEL', state: 'Uttar Pradesh', constituency: 'FATEHPUR', allocatedCr: 14.70 },
  { mpName: 'NARESH GANPAT MHASKE', state: 'Maharashtra', constituency: 'THANE', allocatedCr: 14.70 },
  { mpName: 'NAVEEN JINDAL', state: 'Haryana', constituency: 'KURUKSHETRA', allocatedCr: 14.70 },
  { mpName: 'NEERAJ MAURYA', state: 'Uttar Pradesh', constituency: 'AONLA', allocatedCr: 14.70 },
  { mpName: 'NILESH DNYANDEV LANKE', state: 'Maharashtra', constituency: 'AHMEDNAGAR', allocatedCr: 14.70 },
  { mpName: 'NIMUBEN JAYANTIBHAI BAMBHANIYA', state: 'Gujarat', constituency: 'BHAVNAGAR', allocatedCr: 14.70 },
  { mpName: 'Nishikant Dubey', state: 'Jharkhand', constituency: 'GODDA', allocatedCr: 14.70 },
  { mpName: 'Nitin Jairam Gadkari', state: 'Maharashtra', constituency: 'NAGPUR', allocatedCr: 16.82 },
  { mpName: 'Nityanand Rai', state: 'Bihar', constituency: 'UJJARPUR', allocatedCr: 14.70 },
  { mpName: 'Om Birla', state: 'Rajasthan', constituency: 'KOTA', allocatedCr: 16.39 },
  { mpName: 'Omprakash Bhupalsinh Alias Pawan Rajenimbalkar', state: 'Maharashtra', constituency: 'OSMANABAD', allocatedCr: 18.48 },
  { mpName: 'P C Mohan', state: 'Karnataka', constituency: 'BANGALORE CENTRAL', allocatedCr: 16.00 },
  { mpName: 'Pankaj Chowdhary', state: 'Uttar Pradesh', constituency: 'MAHARAJGANJ_UP', allocatedCr: 14.70 },
  { mpName: 'PARIMAL SUKLABAIDYA', state: 'Assam', constituency: 'SILCHAR', allocatedCr: 14.83 },
  { mpName: 'PARSHOTTAMBHAI RUPALA', state: 'Gujarat', constituency: 'RAJKOT', allocatedCr: 14.70 },
  { mpName: 'PARTHA BHOWMICK', state: 'West Bengal', constituency: 'BARRACKPUR', allocatedCr: 14.70 },
  { mpName: 'Parvatagouda Chandanagouda Gaddigoudar', state: 'Karnataka', constituency: 'BAGALKOT', allocatedCr: 16.75 },
  { mpName: 'PATEL UMESHBHAI BABUBHAI', state: 'The Dadra And Nagar Haveli And Daman And Diu', constituency: 'DAMAN and DIU', allocatedCr: 24.51 },
  { mpName: 'PATHAN YUSUF', state: 'West Bengal', constituency: 'BAHARAMPUR', allocatedCr: 14.70 },
  { mpName: 'PHANI BHUSAN CHOUDHURY', state: 'Assam', constituency: 'BARPETA', allocatedCr: 14.70 },
  { mpName: 'Piyush Vedprakash Goyal', state: 'Maharashtra', constituency: 'MUMBAI NORTH', allocatedCr: 14.70 },
  { mpName: 'PRABHAKAR REDDY VEMIREDDY', state: 'Andhra Pradesh', constituency: 'NELLORE(SC)', allocatedCr: 14.70 },
  { mpName: 'Prabhubhai Nagarbhai Vasava', state: 'Gujarat', constituency: 'BARDOLI(ST)', allocatedCr: 14.70 },
  { mpName: 'Pradan Baruah', state: 'Assam', constituency: 'LAKHIMPUR', allocatedCr: 14.70 },
  { mpName: 'Pradeep Kumar Singh', state: 'Bihar', constituency: 'ARARIA', allocatedCr: 14.70 },
  { mpName: 'PRADEEP PUROHIT', state: 'Odisha', constituency: 'BARGARH', allocatedCr: 14.70 },
  { mpName: 'Pradyut Bordoloi', state: 'Assam', constituency: 'NOWGONG', allocatedCr: 9.80 },
  { mpName: 'Pralhad Venkatesh Joshi', state: 'Karnataka', constituency: 'DHARWAD', allocatedCr: 15.50 },
  { mpName: 'PRANITI SUSHILKUMAR SHINDE', state: 'Maharashtra', constituency: 'SOLAPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Prasun Banerjee', state: 'West Bengal', constituency: 'HOWRAH', allocatedCr: 14.70 },
  { mpName: 'Pratap Chandra Sarangi', state: 'Odisha', constituency: 'BALASORE', allocatedCr: 14.71 },
  { mpName: 'Prataprao Jadhav', state: 'Maharashtra', constituency: 'BULDHANA', allocatedCr: 14.70 },
  { mpName: 'Pratima Mondal', state: 'West Bengal', constituency: 'JOYNAGAR(SC)', allocatedCr: 14.70 },
  { mpName: 'Praveen Khandelwal', state: 'Delhi', constituency: 'CHANDINI CHOWK', allocatedCr: 14.75 },
  { mpName: 'PRAVEEN PATEL', state: 'Uttar Pradesh', constituency: 'PHULPUR', allocatedCr: 15.16 },
  { mpName: 'PRIYA SAROJ', state: 'Uttar Pradesh', constituency: 'MACHHLISHAHR(SC)', allocatedCr: 14.70 },
  { mpName: 'Priyanka Gandhi Vadra', state: 'Kerala', constituency: 'WAYANAD', allocatedCr: 12.25 },
  { mpName: 'PRIYANKA SATISH JARKIHOLI', state: 'Karnataka', constituency: 'CHIKKODI', allocatedCr: 14.70 },
  { mpName: 'Prof Sougata Ray', state: 'West Bengal', constituency: 'DUM DUM', allocatedCr: 14.70 },
  { mpName: 'Prof SP Singh Baghel', state: 'Uttar Pradesh', constituency: 'AGRA(SC)', allocatedCr: 14.70 },
  { mpName: 'PUSHPENDRA SAROJ', state: 'Uttar Pradesh', constituency: 'KAUSHAMBI(SC)', allocatedCr: 14.70 },
  { mpName: 'Putta Mahesh Kumar', state: 'Andhra Pradesh', constituency: 'ELURU', allocatedCr: 14.70 },
  { mpName: 'R.K. CHAUDHARY', state: 'Uttar Pradesh', constituency: 'MOHANLALGANJ(SC)', allocatedCr: 14.70 },
  { mpName: 'RABINDRA NARAYAN BEHERA', state: 'Odisha', constituency: 'JAJPUR(SC)', allocatedCr: 14.71 },
  { mpName: 'RACHNA BANERJEE', state: 'West Bengal', constituency: 'HOOGHLY', allocatedCr: 14.70 },
  { mpName: 'Radha Mohan Singh', state: 'Bihar', constituency: 'PURVI CHAMPARAN', allocatedCr: 14.70 },
  { mpName: 'RADHAKRISHNA', state: 'Karnataka', constituency: 'GULBARGA(SC)', allocatedCr: 14.70 },
  { mpName: 'RADHE SHYAM RATHIYA', state: 'Chhattisgarh', constituency: 'RAIGARH(ST)', allocatedCr: 15.97 },
  { mpName: 'RAHUL GANDHI', state: 'Uttar Pradesh', constituency: 'RAE BARELI', allocatedCr: 14.70 },
  { mpName: 'Rahul Kaswan', state: 'Rajasthan', constituency: 'CHURU', allocatedCr: 14.70 },
  { mpName: 'RAHUL SINGH LODHI', state: 'Madhya Pradesh', constituency: 'DAMOH', allocatedCr: 16.31 },
  { mpName: 'RAJ BHUSHAN CHOUDHARY', state: 'Bihar', constituency: 'MUZAFFARPUR', allocatedCr: 14.70 },
  { mpName: 'RAJ KUMAR ROAT', state: 'Rajasthan', constituency: 'BANSWARA(ST)', allocatedCr: 14.70 },
  { mpName: 'RAJA RAM SINGH', state: 'Bihar', constituency: 'KARAKAT', allocatedCr: 14.70 },
  { mpName: 'RAJABHAU', state: 'Maharashtra', constituency: 'NASHIK', allocatedCr: 15.29 },
  { mpName: 'RAJEEV BHARDWAJ', state: 'Himachal Pradesh', constituency: 'KANGRA', allocatedCr: 17.94 },
  { mpName: 'RAJEEV RAI', state: 'Uttar Pradesh', constituency: 'GHOSI', allocatedCr: 14.70 },
  { mpName: 'RAJESH RANJAN ALIAS PAPPU YADAV', state: 'Bihar', constituency: 'PURNEA', allocatedCr: 14.70 },
  { mpName: 'RAJESH VERMA', state: 'Bihar', constituency: 'KHAGARIA', allocatedCr: 14.70 },
  { mpName: 'Rajeshbhai Naranbhai Chudasama', state: 'Gujarat', constituency: 'JUNAGADH', allocatedCr: 14.70 },
  { mpName: 'Rajiv Pratap Rudy', state: 'Bihar', constituency: 'SARAN', allocatedCr: 14.70 },
  { mpName: 'Rajiv Ranjan (Lalan) Singh', state: 'Bihar', constituency: 'MUNGER', allocatedCr: 14.70 },
  { mpName: 'Rajkumar Chahar', state: 'Uttar Pradesh', constituency: 'FATEHPUR SIKRI', allocatedCr: 14.70 },
  { mpName: 'Rajnath Singh', state: 'Uttar Pradesh', constituency: 'LUCKNOW', allocatedCr: 15.48 },
  { mpName: 'RAJPALSINH MAHENDRASINH JADAV', state: 'Gujarat', constituency: 'PANCHMAHAL', allocatedCr: 14.70 },
  { mpName: 'Raju Bista', state: 'West Bengal', constituency: 'DARJEELING', allocatedCr: 14.70 },
  { mpName: 'RAKESH RATHOR', state: 'Uttar Pradesh', constituency: 'SITAPUR', allocatedCr: 14.70 },
  { mpName: 'RAKIBUL HUSSAIN', state: 'Assam', constituency: 'DHUBRI', allocatedCr: 14.70 },
  { mpName: 'RAM PRASAD CHAUDHARY', state: 'Uttar Pradesh', constituency: 'BASTI', allocatedCr: 20.42 },
  { mpName: 'Ram Shiromani', state: 'Uttar Pradesh', constituency: 'SHRAWASTI', allocatedCr: 15.17 },
  { mpName: 'RAMASAHAYAM RAGHURAM REDDY', state: 'Telangana', constituency: 'KHAMMAM', allocatedCr: 14.70 },
  { mpName: 'RAMASHANKAR RAJBHAR', state: 'Uttar Pradesh', constituency: 'SALEMPUR', allocatedCr: 16.01 },
  { mpName: 'RAMBHUAL NISHAD', state: 'Uttar Pradesh', constituency: 'SULTANPUR', allocatedCr: 15.12 },
  { mpName: 'RAMESH AWASTHI', state: 'Uttar Pradesh', constituency: 'KANPUR', allocatedCr: 14.70 },
  { mpName: 'Ramesh Chandappa Jigajinagi', state: 'Karnataka', constituency: 'BIJAPUR(SC)', allocatedCr: 26.95 },
  { mpName: 'Ramprit Mandal', state: 'Bihar', constituency: 'JHANJHARPUR', allocatedCr: 14.70 },
  { mpName: 'Ramvir Singh Bidhuri', state: 'Delhi', constituency: 'SOUTH DELHI', allocatedCr: 14.76 },
  { mpName: 'RANJIT DUTTA', state: 'Assam', constituency: 'Sonitpur', allocatedCr: 14.70 },
  { mpName: 'Rao Inderjit Singh', state: 'Haryana', constituency: 'GURGAON', allocatedCr: 14.70 },
  { mpName: 'Rao Rajendra Singh', state: 'Rajasthan', constituency: 'JAIPUR RURAL', allocatedCr: 14.70 },
  { mpName: 'Ravi Shankar Prasad', state: 'Bihar', constituency: 'PATNA SAHIB', allocatedCr: 14.70 },
  { mpName: 'RAVINDRA DATTARAM WAIKAR', state: 'Maharashtra', constituency: 'MUMBAI NORTH WEST', allocatedCr: 14.70 },
  { mpName: 'Ravindra Shyamnarayan Alias Ravi Kishan Shukla', state: 'Uttar Pradesh', constituency: 'GORAKHPUR', allocatedCr: 14.70 },
  { mpName: 'Ravindra Vasantrao Chavan', state: 'Maharashtra', constituency: 'NANDED', allocatedCr: 14.70 },
  { mpName: 'RICHARD VANLALHMANGAIHA', state: 'Mizoram', constituency: 'MIZORAM (ST)', allocatedCr: 14.70 },
  { mpName: 'ROBERT BRUCE C', state: 'Tamil Nadu', constituency: 'TIRUNELVELI', allocatedCr: 14.75 },
  { mpName: 'Rodmal Nagar', state: 'Madhya Pradesh', constituency: 'RAJGARH', allocatedCr: 14.70 },
  { mpName: 'ROOP KUMARI CHOUDHARY', state: 'Chhattisgarh', constituency: 'MAHASAMUND', allocatedCr: 15.30 },
  { mpName: 'RUCHI VIRA', state: 'Uttar Pradesh', constituency: 'MORADABAD', allocatedCr: 14.70 },
  { mpName: 'RUDRA NARAYAN PANY', state: 'Odisha', constituency: 'DHENKANAL', allocatedCr: 15.50 },
  { mpName: 'S SUPONGMEREN JAMIR', state: 'Nagaland', constituency: 'NAGALAND', allocatedCr: 14.70 },
  { mpName: 'S Venkatesan', state: 'Tamil Nadu', constituency: 'MADURAI', allocatedCr: 14.70 },
  { mpName: 'S. Jagathrakshakan', state: 'Tamil Nadu', constituency: 'ARAKKONAM', allocatedCr: 18.06 },
  { mpName: 'SACHITHANANTHAM R', state: 'Tamil Nadu', constituency: 'DINDIGUL', allocatedCr: 14.70 },
  { mpName: 'SAGAR ESHWAR KHANDRE', state: 'Karnataka', constituency: 'BIDAR', allocatedCr: 14.70 },
  { mpName: 'SALENG A SANGMA', state: 'Meghalaya', constituency: 'TURA', allocatedCr: 14.70 },
  { mpName: 'SAMBIT PATRA', state: 'Odisha', constituency: 'PURI', allocatedCr: 14.70 },
  { mpName: 'SANATAN PANDEY', state: 'Uttar Pradesh', constituency: 'BALLIA', allocatedCr: 18.04 },
  { mpName: 'SANJAY DINA PATIL', state: 'Maharashtra', constituency: 'MUMBAI NORTH EAST', allocatedCr: 14.70 },
  { mpName: 'Sanjay Haribhau Jadhav', state: 'Maharashtra', constituency: 'PARBHANI', allocatedCr: 14.70 },
  { mpName: 'Sanjay Jaiswal', state: 'Bihar', constituency: 'PASCHIM CHAMPARAN', allocatedCr: 14.70 },
  { mpName: 'Sanjay Kumar Bandi', state: 'Telangana', constituency: 'KARIMNAGAR', allocatedCr: 17.28 },
  { mpName: 'Sanjay Seth', state: 'Jharkhand', constituency: 'RANCHI', allocatedCr: 14.71 },
  { mpName: 'Sanjay Uttamrao Deshmukh', state: 'Maharashtra', constituency: 'YAVATMAL-WASHIM', allocatedCr: 18.56 },
  { mpName: 'SANJNA JATAV', state: 'Rajasthan', constituency: 'BHARATPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Santosh Pandey', state: 'Chhattisgarh', constituency: 'RAJNANDGAON', allocatedCr: 14.70 },
  { mpName: 'Saptagiri Sankar Ulaka', state: 'Odisha', constituency: 'KORAPUT(ST)', allocatedCr: 26.95 },
  { mpName: 'SARABJEET SINGH KHALSA', state: 'Punjab', constituency: 'FARIDKOT(SC)', allocatedCr: 15.09 },
  { mpName: 'Sasikanth Senthil', state: 'Tamil Nadu', constituency: 'TIRUVALLUR(SC)', allocatedCr: 17.15 },
  { mpName: 'SATPAL BRAHAMCHARI', state: 'Haryana', constituency: 'SONEPAT', allocatedCr: 14.70 },
  { mpName: 'Saumitra khan', state: 'West Bengal', constituency: 'BISHNUPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'SAVITRI THAKUR', state: 'Madhya Pradesh', constituency: 'DHAR(ST)', allocatedCr: 14.70 },
  { mpName: 'SAYANI GHOSH', state: 'West Bengal', constituency: 'JADAVPUR', allocatedCr: 14.70 },
  { mpName: 'SELJA', state: 'Haryana', constituency: 'SIRSA(SC)', allocatedCr: 14.70 },
  { mpName: 'SELVAGANAPATHI T M', state: 'Tamil Nadu', constituency: 'SALEM', allocatedCr: 14.70 },
  { mpName: 'SELVARAJ V', state: 'Tamil Nadu', constituency: 'NAGAPATTINAM(SC)', allocatedCr: 14.70 },
  { mpName: 'SHAFI PARAMBIL', state: 'Kerala', constituency: 'VADAKARA', allocatedCr: 14.70 },
  { mpName: 'SHAMBHAVI', state: 'Bihar', constituency: 'SAMASTIPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Shankar Lalwani', state: 'Madhya Pradesh', constituency: 'INDORE', allocatedCr: 14.70 },
  { mpName: 'SHASHANK MANI', state: 'Uttar Pradesh', constituency: 'DEORIA', allocatedCr: 14.70 },
  { mpName: 'Shatrughan Sinha', state: 'West Bengal', constituency: 'ASANSOL', allocatedCr: 14.70 },
  { mpName: 'SHER SINGH GHUBAYA', state: 'Punjab', constituency: 'FIROZPUR', allocatedCr: 14.70 },
  { mpName: 'SHIVMANGAL SINGH TOMAR', state: 'Madhya Pradesh', constituency: 'MORENA', allocatedCr: 14.70 },
  { mpName: 'SHIVRAJ SINGH CHOUHAN', state: 'Madhya Pradesh', constituency: 'VIDISHA', allocatedCr: 14.70 },
  { mpName: 'SHOBHA KARANDLAJE', state: 'Karnataka', constituency: 'BANGALORE NORTH', allocatedCr: 14.70 },
  { mpName: 'SHOBHANABEN MAHENDRASINH BARAIYA', state: 'Gujarat', constituency: 'SABARKANTHA', allocatedCr: 14.70 },
  { mpName: 'SHREYAS. M. PATEL', state: 'Karnataka', constituency: 'HASSAN', allocatedCr: 14.70 },
  { mpName: 'Shri Dharambir Singh', state: 'Haryana', constituency: 'BHIWANI MAHENDRAGARH', allocatedCr: 14.70 },
  { mpName: 'Shri Abhishek Banerjee', state: 'West Bengal', constituency: 'DIAMOND HARBOUR', allocatedCr: 14.70 },
  { mpName: 'Shri Amar Singh', state: 'Punjab', constituency: 'FATEHGARH SAHIB(SC)', allocatedCr: 14.70 },
  { mpName: 'Shri Amit Shah', state: 'Gujarat', constituency: 'GANDHINAGAR', allocatedCr: 14.70 },
  { mpName: 'Shri Anil Firojiya', state: 'Madhya Pradesh', constituency: 'UJJAIN(SC)', allocatedCr: 14.70 },
  { mpName: 'Shri Arjun Ram Meghwal', state: 'Rajasthan', constituency: 'BIKANER(SC)', allocatedCr: 14.70 },
  { mpName: 'Shri Arun Kumar Sagar', state: 'Uttar Pradesh', constituency: 'SHAHJAHANPUR(SC)', allocatedCr: 14.70 },
  { mpName: 'Shri B Y Raghavendra', state: 'Karnataka', constituency: 'SHIMOGA', allocatedCr: 14.70 },
  { mpName: 'Shri Benny Behanan', state: 'Kerala', constituency: 'CHALAKUDY', allocatedCr: 16.47 },
  { mpName: 'Shri Bhartruhari Mahtab', state: 'Odisha', constituency: 'CUTTACK', allocatedCr: 14.70 },
  { mpName: 'Shri Chandra Prakash Choudhary', state: 'Jharkhand', constituency: 'GIRIDIH', allocatedCr: 14.70 },
  { mpName: 'Shri Deepak (Dev) Adhikari', state: 'West Bengal', constituency: 'GHATAL', allocatedCr: 20.07 },
  { mpName: 'Shri Gurjeet Singh Aujla', state: 'Punjab', constituency: 'AMRITSAR', allocatedCr: 14.70 },
  { mpName: 'Shri Hanuman Beniwal', state: 'Rajasthan', constituency: 'NAGAUR', allocatedCr: 14.70 },
  { mpName: 'Shri Hibi Eden', state: 'Kerala', constituency: 'ERNAKULAM', allocatedCr: 16.22 },
  { mpName: 'Shri Janardan Singh Sigriwal', state: 'Bihar', constituency: 'MAHARAJGANJ_BR', allocatedCr: 14.70 },
  { mpName: 'Shri Jual Oram', state: 'Odisha', constituency: 'SUNDARGARH (ST)', allocatedCr: 17.31 },
  { mpName: 'Shri Jugal Kishore Sharma', state: 'Jammu And Kashmir', constituency: 'JAMMU', allocatedCr: 14.70 },
  { mpName: 'Shri Jyotirmay Singh Mahato', state: 'West Bengal', constituency: 'PURULIA', allocatedCr: 14.70 },
  { mpName: 'Shri Karti P Chidambaram', state: 'Tamil Nadu', constituency: 'SIVAGANGA', allocatedCr: 15.90 },
  { mpName: 'Shri Kumbakudi Sudhakaran', state: 'Kerala', constituency: 'KANNUR', allocatedCr: 14.70 },
  { mpName: 'Shri LS Tejasvi Surya', state: 'Karnataka', constituency: 'BANGALORE SOUTH', allocatedCr: 14.70 },
  { mpName: 'Shri M K Raghavan', state: 'Kerala', constituency: 'KOZHIKODE', allocatedCr: 14.70 },
  { mpName: 'Shri Narendra Modi', state: 'Uttar Pradesh', constituency: 'VARANASI', allocatedCr: 16.21 },
  { mpName: 'Shri NK Premachandran', state: 'Kerala', constituency: 'KOLLAM', allocatedCr: 17.15 },
  { mpName: 'Shri PP Chaudhary', state: 'Rajasthan', constituency: 'PALI', allocatedCr: 14.70 },
  { mpName: 'Shri Rajmohan Unnithan', state: 'Kerala', constituency: 'KASARAGOD', allocatedCr: 15.68 },
  { mpName: 'Shri Sarbananda Sonowal (18LS)', state: 'Assam', constituency: 'DIBRUGARH', allocatedCr: 14.70 },
  { mpName: 'Shri Satish Kumar Gautam', state: 'Uttar Pradesh', constituency: 'ALIGARH', allocatedCr: 14.70 },
  { mpName: 'Shri Shantanu Thakur', state: 'West Bengal', constituency: 'BANGAON(SC)', allocatedCr: 14.70 },
  { mpName: 'Shri Sudheer Gupta', state: 'Madhya Pradesh', constituency: 'MANDSOUR', allocatedCr: 14.90 },
  { mpName: 'Shri Suresh Kodikunnil', state: 'Kerala', constituency: 'MAVELIKKARA(SC)', allocatedCr: 17.24 },
  { mpName: 'Shri Tapir Gao', state: 'Arunachal Pradesh', constituency: 'ARUNACHAL EAST', allocatedCr: 14.70 },
  { mpName: 'Shri vijayakumar Vasanth', state: 'Tamil Nadu', constituency: 'KANNIYAKUMARI', allocatedCr: 17.15 },
  { mpName: 'Shrikant Eknath Shinde', state: 'Maharashtra', constituency: 'KALYAN', allocatedCr: 14.70 },
  { mpName: 'SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHONSLE', state: 'Maharashtra', constituency: 'SATARA', allocatedCr: 14.70 },
  { mpName: 'Shripad Yesso Naik', state: 'Goa', constituency: 'NORTH GOA', allocatedCr: 14.70 },
  { mpName: 'Shrirang Appa Barne', state: 'Maharashtra', constituency: 'MAVAL', allocatedCr: 14.70 },
  { mpName: 'Shyamkumar', state: 'Maharashtra', constituency: 'RAMTEK(SC)', allocatedCr: 14.70 },
  { mpName: 'Sivanath Kesineni', state: 'Andhra Pradesh', constituency: 'VIJAYAWADA', allocatedCr: 15.99 },
  { mpName: 'SK NURUL ISLAM', state: 'West Bengal', constituency: 'BASIRHAT', allocatedCr: 4.90 },
  { mpName: 'SMITA UDAY WAGH', state: 'Maharashtra', constituency: 'JALGAON', allocatedCr: 14.81 },
  { mpName: 'Smt Anupriya Patel', state: 'Uttar Pradesh', constituency: 'MIRZAPUR', allocatedCr: 14.70 },
  { mpName: 'Smt Aparajita Sarangi', state: 'Odisha', constituency: 'BHUBANESWAR', allocatedCr: 14.74 },
  { mpName: 'Smt Dimple Yadav', state: 'Uttar Pradesh', constituency: 'MAINPURI', allocatedCr: 19.20 },
  { mpName: 'Smt Harsimrat Kaur Badal', state: 'Punjab', constituency: 'BHATINDA', allocatedCr: 15.98 },
  { mpName: 'Smt Hema Malini', state: 'Uttar Pradesh', constituency: 'MATHURA', allocatedCr: 14.70 },
  { mpName: 'Smt Himadri Singh', state: 'Madhya Pradesh', constituency: 'SHAHDOL (ST)', allocatedCr: 15.07 },
  { mpName: 'Smt Poonamben Hematbhai Maadam', state: 'Gujarat', constituency: 'JAMNAGAR', allocatedCr: 14.70 },
  { mpName: 'Smt Raksha Nikhil Khadse', state: 'Maharashtra', constituency: 'RAVER', allocatedCr: 15.31 },
  { mpName: 'Smt S Jothimani', state: 'Tamil Nadu', constituency: 'KARUR', allocatedCr: 14.70 },
  { mpName: 'Smt Sajda Ahmed', state: 'West Bengal', constituency: 'ULUBERIA', allocatedCr: 14.70 },
  { mpName: 'Smt Sandhya Ray', state: 'Madhya Pradesh', constituency: 'BHIND(SC)', allocatedCr: 14.70 },
  { mpName: 'Smt Sangeeta Kumari Singh Deo', state: 'Odisha', constituency: 'BOLANGIR', allocatedCr: 14.70 },
  { mpName: 'Smt Satabdi Roy (Banerjee)', state: 'West Bengal', constituency: 'BIRBHUM', allocatedCr: 14.70 },
  { mpName: 'Smt Supriya Sadanand Sule', state: 'Maharashtra', constituency: 'BARAMATI', allocatedCr: 14.70 },
  { mpName: 'Smt Veena Devi', state: 'Bihar', constituency: 'VAISHALI', allocatedCr: 14.70 },
  { mpName: 'Sribharat MathuKumli', state: 'Andhra Pradesh', constituency: 'VISAKHAPATNAM', allocatedCr: 16.48 },
  { mpName: 'SUDAMA PRASAD', state: 'Bihar', constituency: 'ARRAH', allocatedCr: 14.70 },
  { mpName: 'SUDHA R', state: 'Tamil Nadu', constituency: 'MAYILADUTHURAI', allocatedCr: 14.73 },
  { mpName: 'SUDHAKAR SINGH', state: 'Bihar', constituency: 'BUXAR', allocatedCr: 18.52 },
  { mpName: 'Sudip Bandyopadhyay', state: 'West Bengal', constituency: 'KOLKATA UTTAR', allocatedCr: 14.70 },
  { mpName: 'SUKANTA KUMAR PANIGRAHI', state: 'Odisha', constituency: 'KANDHAMAL', allocatedCr: 19.07 },
  { mpName: 'SUKHDEO BHAGAT', state: 'Jharkhand', constituency: 'LOHARDAGA(ST)', allocatedCr: 17.18 },
  { mpName: 'SUKHJINDER SINGH RANDHAWA', state: 'Punjab', constituency: 'GURDASPUR', allocatedCr: 14.70 },
  { mpName: 'SUNIL BOSE', state: 'Karnataka', constituency: 'CHAMARAJANAGAR(SC)', allocatedCr: 14.70 },
  { mpName: 'Sunil Dattatray Tatkare', state: 'Maharashtra', constituency: 'RAIGAD', allocatedCr: 14.70 },
  { mpName: 'Sunil Kumar', state: 'Bihar', constituency: 'VALMIKI NAGAR', allocatedCr: 14.70 },
  { mpName: 'SURENDRA PRASAD YADAV', state: 'Bihar', constituency: 'JAHANABAD', allocatedCr: 15.53 },
  { mpName: 'SURESH GOPI', state: 'Kerala', constituency: 'THRISSUR', allocatedCr: 14.70 },
  { mpName: 'Suresh Kumar Kashyap', state: 'Himachal Pradesh', constituency: 'SHIMLA (SC)', allocatedCr: 15.36 },
  { mpName: 'SURESH KUMAR SHETKAR', state: 'Telangana', constituency: 'ZAHIRABAD', allocatedCr: 14.70 },
  { mpName: 'Swami Sachchidanandhari Sakshi ji Maharaj', state: 'Uttar Pradesh', constituency: 'UNNAO', allocatedCr: 14.70 },
  { mpName: 'T Sumathy (A) Thamizhachi Thangapandian', state: 'Tamil Nadu', constituency: 'CHENNAI SOUTH', allocatedCr: 14.70 },
  { mpName: 'TANGELLA UDAY SRINIVAS', state: 'Andhra Pradesh', constituency: 'KAKINADA', allocatedCr: 19.94 },
  { mpName: 'TANUJ PUNIA', state: 'Uttar Pradesh', constituency: 'BARABANKI(SC)', allocatedCr: 14.82 },
  { mpName: 'TARIQ ANWAR', state: 'Bihar', constituency: 'KATIHAR', allocatedCr: 14.70 },
  { mpName: 'Thalikkottai Rajuthevar Baalu', state: 'Tamil Nadu', constituency: 'SRIPERUMBUDUR', allocatedCr: 19.69 },
  { mpName: 'THANGA TAMILSELVAN', state: 'Tamil Nadu', constituency: 'THENI', allocatedCr: 16.78 },
  { mpName: 'THARANIVENTHAN M S', state: 'Tamil Nadu', constituency: 'ARANI', allocatedCr: 16.83 },
  { mpName: 'Thiru Dayanidhi Maran', state: 'Tamil Nadu', constituency: 'CHENNAI CENTRAL', allocatedCr: 14.70 },
  { mpName: 'Thirumaa Valavan Thol', state: 'Tamil Nadu', constituency: 'CHIDAMBARAM(SC)', allocatedCr: 14.70 },
  { mpName: 'TOKHAN SAHU', state: 'Chhattisgarh', constituency: 'BILASPUR', allocatedCr: 14.70 },
  { mpName: 'TRIVENDRA SINGH RAWAT', state: 'Uttarakhand', constituency: 'HARDWAR', allocatedCr: 14.70 },
  { mpName: 'UJJWAL RAMAN SINGH', state: 'Uttar Pradesh', constituency: 'ALLAHABAD', allocatedCr: 14.70 },
  { mpName: 'UMMEDA RAM BENIWAL', state: 'Rajasthan', constituency: 'BARMER', allocatedCr: 14.70 },
  { mpName: 'UTKARSH VERMA MADHUR', state: 'Uttar Pradesh', constituency: 'KHERI', allocatedCr: 14.70 },
  { mpName: 'V S Matheswaran', state: 'Tamil Nadu', constituency: 'NAMAKKAL', allocatedCr: 16.25 },
  { mpName: 'V. SOMANNA', state: 'Karnataka', constituency: 'TUMKUR', allocatedCr: 14.70 },
  { mpName: 'Vaithilingam Ve', state: 'Puducherry', constituency: 'Puducherry', allocatedCr: 20.94 },
  { mpName: 'VAMSI KRISHNA GADDAM', state: 'Telangana', constituency: 'PEDDAPALLE', allocatedCr: 14.85 },
  { mpName: 'VARUN CHAUDHRY', state: 'Haryana', constituency: 'AMBALA (SC)', allocatedCr: 25.55 },
  { mpName: 'Vellalath Kochukrishnan Nair Sreekandan', state: 'Kerala', constituency: 'PALAKKAD', allocatedCr: 16.78 },
  { mpName: 'Vijay Baghel', state: 'Chhattisgarh', constituency: 'DURG', allocatedCr: 14.70 },
  { mpName: 'Vijay Kumar Dubey', state: 'Uttar Pradesh', constituency: 'KUSHI NAGAR', allocatedCr: 14.89 },
  { mpName: 'Vijay Kumar Hansdak', state: 'Jharkhand', constituency: 'RAJMAHAL(ST)', allocatedCr: 14.72 },
  { mpName: 'VIJAYLAKSHMI DEVI', state: 'Bihar', constituency: 'SIWAN', allocatedCr: 14.70 },
  { mpName: 'Vinod Chavda', state: 'Gujarat', constituency: 'KACHCHH(SC)', allocatedCr: 14.70 },
  { mpName: 'VINOD KUMAR BIND', state: 'Uttar Pradesh', constituency: 'BHADOHI', allocatedCr: 14.70 },
  { mpName: 'Virendra Kumar', state: 'Madhya Pradesh', constituency: 'TIKAMGARH(SC)', allocatedCr: 14.70 },
  { mpName: 'VIRENDRA SINGH', state: 'Uttar Pradesh', constituency: 'CHANDAULI', allocatedCr: 14.70 },
  { mpName: 'VISHAL', state: 'Maharashtra', constituency: 'SANGLI', allocatedCr: 14.70 },
  { mpName: 'Vishnu Dayal Ram', state: 'Jharkhand', constituency: 'PALAMU(SC)', allocatedCr: 15.82 },
  { mpName: 'Vishnu Dutt Sharma', state: 'Madhya Pradesh', constituency: 'KHAJURAHO', allocatedCr: 14.70 },
  { mpName: 'VISHWESHWAR HEGDE KAGERI', state: 'Karnataka', constituency: 'UTTARA KANNADA', allocatedCr: 14.70 },
  { mpName: 'VIVEK THAKUR', state: 'Bihar', constituency: 'NAWADA', allocatedCr: 14.70 },
  { mpName: 'Y S Avinash Reddy', state: 'Andhra Pradesh', constituency: 'KADAPA', allocatedCr: 15.64 },
  { mpName: 'YADUVEER KRISHNADATTA CHAMARAJA WADIYAR', state: 'Karnataka', constituency: 'MYSORE', allocatedCr: 14.70 },
  { mpName: 'Yogendra Chandoliya', state: 'Delhi', constituency: 'NORTH WEST DELHI(SC)', allocatedCr: 14.79 },
  { mpName: 'ZIA UR REHMAN', state: 'Uttar Pradesh', constituency: 'SAMBHAL', allocatedCr: 14.70 },
];

export const MP_ALLOCATION_TOTAL_CR = 8341.94;
export const MP_ALLOCATION_COUNT = 543;
