from __future__ import annotations

from app.core.config import STATE_NAME

"""Comprehensive realistic seed data across 5 districts in Telangana / Andhra Pradesh:
Hyderabad, Rangareddy, Medchal-Malkajgiri, Sangareddy, Mahbubnagar.
Includes 20 realistic Cases with full test scenario coverage:
- 2 Spatial & Title Duplicates (<300m away, >88% title match)
- 2 Log-Cost Inflated Cases (Robust Z-score > +3.2)
- 2 Hard-Gate Violations (Non-public land tenure, forged pHash photo match)
- 1 Ghost Completion Case (90% funds disbursed, 10% physical progress)
- 1 PFMS Redirection Alert Case
- 12 Clean and diverse community infrastructure works
"""

CASES = [
    # 1. Duplicate Work A (Hyderabad)
    {
        "id": "MPL-2025-1001",
        "title": "Community Knowledge & Study Centre, Ward 14, Amberpet, Hyderabad",
        "hindiTitle": "सामुदायिक ज्ञान एवं अध्ययन केंद्र, वार्ड 14, अंबरपेट, हैदराबाद",
        "category": "Community Assets",
        "state": STATE_NAME,
        "district": "Hyderabad",
        "constituency": "Secunderabad",
        "mpName": "Shri Anant Rao (Demo Constituency)",
        "dmName": "DM Sharma (Demo)",
        "sanctionedAmountLakh": 16.5,
        "sanctionedDate": "12 Jun 2025",
        "status": "hold_active",
        "statusSince": "15 Jul 2025",
        "overview": "Proposed community knowledge centre overlaps with an existing sanctioned digital library building just 160 m away. Text similarity is 89%.",
        "mpPlainStatus": "Held automatically because a nearly identical study centre was already sanctioned 160m away.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "geo": {"lat": 17.3850, "lng": 78.4867},
            "trend": {"case_release_pct": 40, "peer_release_pct": 72, "peer_sd": 14},
            "duplicate": {
                "twin": {
                    "title": "Community Knowledge & Study Centre, Ward 16, Amberpet, Hyderabad",
                    "id": "MPL-2025-1002",
                    "distance_m": 160,
                    "lat": 17.3864372,
                    "lng": 78.4867,
                    "map_x": 48,
                    "map_y": 52,
                }
            },
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 2},
            "predictive": {"factors": []},
            "compliance": {
                "checks": [
                    {"field": "Duplicate overlap check", "actual": "Recommended duplicate (ADR-11)", "required": "No overlap", "rule_ref": "ADR-11", "clause_text": "Pre-approval overlap scan vs active sanctioned works.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Public (GHMC Revenue)", "required": "Public / Municipal", "rule_ref": "OP 2025–26 §4.1.3", "clause_text": "Works on public or municipal land.", "critical": True, "passed": True},
                    {"field": "Entity type", "actual": "Public agency (GHMC)", "required": "Eligible entity", "rule_ref": "OP 2025–26 §2.1", "clause_text": "Implementing agency eligible.", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 2. Duplicate Work B (Twin of #1, Hyderabad)
    {
        "id": "MPL-2025-1002",
        "title": "Community Knowledge & Study Centre, Ward 16, Amberpet, Hyderabad",
        "hindiTitle": "सामुदायिक ज्ञान एवं अध्ययन केंद्र, वार्ड 16, अंबरपेट",
        "category": "Community Assets",
        "state": STATE_NAME,
        "district": "Hyderabad",
        "constituency": "Secunderabad",
        "mpName": "Shri G. Kishan Reddy",
        "dmName": "DM Sharma (Demo)",
        "sanctionedAmountLakh": 15.0,
        "sanctionedDate": "10 Jan 2025",
        "status": "released",
        "statusSince": "20 May 2025",
        "overview": "Original sanctioned library centre at Amberpet currently in active physical execution.",
        "mpPlainStatus": "Work in progress on schedule. 70% physical completion achieved.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 75, "peer_release_pct": 72, "peer_sd": 10},
            "payment": {"released_pct": 70, "completion_pct": 75, "months_since_sanction": 6},
            "predictive": {"factors": []},
            "compliance": {
                "checks": [
                    {"field": "Land ownership", "actual": "Public (GHMC)", "required": "Public / Municipal", "rule_ref": "OP 2025–26 §4.1.3", "clause_text": "Works on public land.", "critical": True, "passed": True},
                    {"field": "Entity type", "actual": "Public agency", "required": "Eligible entity", "rule_ref": "OP 2025–26 §2.1", "clause_text": "Implementing agency eligible.", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 3. Duplicate Work C (Medchal-Malkajgiri)
    {
        "id": "MPL-2025-1003",
        "title": "Construction of CC Road and Storm Drain, Pragathi Nagar, Medchal",
        "hindiTitle": "सीसी सड़क एवं नाली निर्माण, प्रगति नगर, मेडचल",
        "category": "Rural Roads",
        "state": STATE_NAME,
        "district": "Medchal-Malkajgiri",
        "constituency": "Malkajgiri",
        "mpName": "Shri Vikram Rathore (Demo Constituency)",
        "dmName": "DM Iyer (Demo)",
        "sanctionedAmountLakh": 24.0,
        "sanctionedDate": "04 Jul 2025",
        "status": "hold_active",
        "statusSince": "18 Aug 2025",
        "overview": "Identical CC Road and storm drain sanctioned 210m from an active municipal road project with 91% description overlap.",
        "mpPlainStatus": "Held due to 91% duplicate match with existing road work in Pragathi Nagar.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "geo": {"lat": 17.4500, "lng": 78.4800},
            "trend": {"case_release_pct": 30, "peer_release_pct": 65, "peer_sd": 12},
            "duplicate": {
                "twin": {
                    "title": "Laying of CC Road and Storm Drain, Pragathi Nagar, Medchal",
                    "id": "MPL-2025-1004",
                    "distance_m": 210,
                    "lat": 17.4518863,
                    "lng": 78.4800,
                    "map_x": 62,
                    "map_y": 38,
                }
            },
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 2},
            "predictive": {"factors": []},
            "compliance": {
                "checks": [
                    {"field": "Duplicate overlap check", "actual": "Spatial duplicate flagged", "required": "No overlap", "rule_ref": "ADR-11", "clause_text": "Overlap scan vs active works.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Public road right of way", "required": "Public / Municipal", "rule_ref": "OP 2025–26 §4.1.3", "clause_text": "Public land corridor.", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 4. Duplicate Twin of #3 (Medchal-Malkajgiri)
    {
        "id": "MPL-2025-1004",
        "title": "Laying of CC Road and Storm Drain, Pragathi Nagar, Medchal",
        "hindiTitle": "सीसी सड़क एवं नाली बिछाना, प्रगति नगर, मेडचल",
        "category": "Rural Roads",
        "state": STATE_NAME,
        "district": "Medchal-Malkajgiri",
        "constituency": "Malkajgiri",
        "mpName": "Shri Eatala Rajender",
        "dmName": "DM Iyer (Demo)",
        "sanctionedAmountLakh": 22.5,
        "sanctionedDate": "15 Feb 2025",
        "status": "released",
        "statusSince": "10 Mar 2025",
        "overview": "Original sanctioned CC road work at Pragathi Nagar in advanced construction stage.",
        "mpPlainStatus": "Work executing on schedule with regular inspection milestones.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 80, "peer_release_pct": 65, "peer_sd": 10},
            "payment": {"released_pct": 75, "completion_pct": 80, "months_since_sanction": 6},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Public", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 5. Cost Outlier Case 1 (Sangareddy - Z-score > +3.2)
    {
        "id": "MPL-2025-1005",
        "title": "Rural Link CC Road, Zaheerabad to Kohir Feeder km 0-3.5, Sangareddy",
        "hindiTitle": "ग्रामीण लिंक सीसी रोड, जहीराबाद से कोहिर फीडर किमी 0-3.5",
        "category": "Rural Roads",
        "state": STATE_NAME,
        "district": "Sangareddy",
        "constituency": "Zaheerabad",
        "mpName": "Shri Harish Chandran (Demo Constituency)",
        "dmName": "DM Nair (Demo)",
        "sanctionedAmountLakh": 48.5,
        "sanctionedDate": "02 May 2025",
        "status": "escalated",
        "statusSince": "22 Jun 2025",
        "overview": "Sanctioned at ₹48.5 Lakh against district median baseline of ₹22.0 Lakh for comparable rural road works. Robust MAD Z-score is +3.45.",
        "mpPlainStatus": "Escalated to engineering audit due to cost variance (+120% above district benchmark).",
        "path": ["submitted", "evaluating", "hold_active", "escalated"],
        "facts": {
            "trend": {"case_release_pct": 25, "peer_release_pct": 60, "peer_sd": 15},
            "payment": {"released_pct": 20, "completion_pct": 10, "months_since_sanction": 4},
            "predictive": {"factors": ["Cost estimate exceeds standard Schedule of Rates"]},
            "compliance": {
                "checks": [
                    {"field": "BOQ benchmarking", "actual": "Exceeds standard SOR by 120%", "required": "Benchmarked BOQ", "rule_ref": "OP 2025–26 §5.1", "clause_text": "BOQ rates benchmarked against State PWD schedule.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Public road corridor", "required": "Public / Municipal", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 6. Cost Outlier Case 2 (Mahbubnagar - Z-score > +3.2)
    {
        "id": "MPL-2025-1006",
        "title": "High-Mast Solar LED Streetlighting Array, Jadcherla Junction, Mahbubnagar",
        "hindiTitle": "हाई-मास्ट सोलर एलईडी स्ट्रीटलाइटिंग, जदचेरला जंक्शन",
        "category": "Renewable Energy",
        "state": STATE_NAME,
        "district": "Mahbubnagar",
        "constituency": "Mahbubnagar",
        "mpName": "Smt. Devika Balan (Demo Constituency)",
        "dmName": "DM Rao (Demo)",
        "sanctionedAmountLakh": 36.0,
        "sanctionedDate": "14 Apr 2025",
        "status": "hold_active",
        "statusSince": "28 May 2025",
        "overview": "Sanctioned ₹36.0 Lakh for 10 solar LED mast units against benchmark median of ₹14.0 Lakh. Robust Z-score is +3.32.",
        "mpPlainStatus": "Held for cost re-verification — unit rates are 157% higher than TSREDCO approved tariffs.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 35, "peer_release_pct": 68, "peer_sd": 14},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 3},
            "predictive": {"factors": ["Vendor quote non-competitive"]},
            "compliance": {
                "checks": [
                    {"field": "Technical sanction rate", "actual": "157% above TSREDCO rate", "required": "Tariff compliant", "rule_ref": "OP 2025–26 §5.2", "clause_text": "Rates aligned with nodal renewable agency schedule.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Public traffic junction", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 7. Hard-Gate Violation 1 (Rangareddy - Non-public land tenure)
    {
        "id": "MPL-2025-1007",
        "title": "Community Function Hall at Sri Sai Enclave, Rajendranagar, Rangareddy",
        "hindiTitle": "सामुदायिक भवन, श्री साई एन्क्लेव, राजेंद्रनगर",
        "category": "Community Assets",
        "state": STATE_NAME,
        "district": "Rangareddy",
        "constituency": "Chevella",
        "mpName": "Shri Anant Rao (Demo Constituency)",
        "dmName": "DM Verma (Demo)",
        "sanctionedAmountLakh": 28.0,
        "sanctionedDate": "05 Jun 2025",
        "status": "hold_active",
        "statusSince": "12 Jun 2025",
        "overview": "CRITICAL COMPLIANCE GATE FIRED: Proposal site is situated on private un-regularised society land. MPLADS guidelines mandate clear public/municipal ownership.",
        "mpPlainStatus": "HARD GATE HOLD: Cannot proceed because land is private/un-regularised. Requires public title conveyance.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 0, "peer_release_pct": 50, "peer_sd": 12},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 2},
            "predictive": {"factors": ["Land ownership title dispute"]},
            "compliance": {
                "checks": [
                    {
                        "field": "Land ownership",
                        "actual": "Private gated society land (Sy No. 142/A)",
                        "required": "Public / Municipal Land",
                        "rule_ref": "OP 2025–26 §4.1.3",
                        "clause_text": "MPLADS funds can only create assets on land belonging to Government or local body.",
                        "critical": True,
                        "passed": False,
                    },
                    {
                        "field": "Entity type",
                        "actual": "Private Resident Welfare Association",
                        "required": "Eligible Public Entity",
                        "rule_ref": "OP 2025–26 §2.1",
                        "clause_text": "Implementing agency must be an authorized public department.",
                        "critical": True,
                        "passed": False,
                    },
                ]
            },
        },
    },
    # 8. Hard-Gate Violation 2 (Hyderabad - Forged Photo Integrity pHash >= 99%)
    {
        "id": "MPL-2025-1008",
        "title": "Modernization of Urban Health Post, Yakutpura, Hyderabad",
        "hindiTitle": "शहरी स्वास्थ्य केंद्र का आधुनिकीकरण, याकूतपुरा",
        "category": "Health & Sanitation",
        "state": STATE_NAME,
        "district": "Hyderabad",
        "constituency": "Hyderabad",
        "mpName": "Shri Vikram Rathore (Demo Constituency)",
        "dmName": "DM Sharma (Demo)",
        "sanctionedAmountLakh": 19.5,
        "sanctionedDate": "18 Mar 2025",
        "status": "hold_active",
        "statusSince": "25 May 2025",
        "overview": "CRITICAL PHOTO GATE FIRED: Uploaded Stage-2 completion photographs match photos submitted under MPL-2024-0341 with 99.6% perceptual hash similarity.",
        "mpPlainStatus": "HARD GATE HOLD: Uploaded site inspection photo is identical to a prior year clinic in another ward.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 50, "peer_release_pct": 70, "peer_sd": 10},
            "photo": {
                "phash_match_pct": 99.6,
                "twin_case_id": "MPL-2024-0341",
                "exif_discrepancy": "EXIF camera serial and GPS coordinate point to Charminar dispensary taken in 2024.",
            },
            "payment": {"released_pct": 50, "completion_pct": 20, "months_since_sanction": 5},
            "predictive": {"factors": ["Staged photographic documentation"]},
            "compliance": {
                "checks": [
                    {"field": "Photographic stage verification", "actual": "Duplicate image reused (pHash 99.6%)", "required": "Authentic geotagged photos", "rule_ref": "OP 2025–26 §8.3", "clause_text": "Stage photos must be uniquely captured with live timestamp & GPS.", "critical": True, "passed": False},
                    {"field": "Land ownership", "actual": "Public Health Department", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 9. Ghost Completion Case (Sangareddy - 90% released, 10% progress)
    {
        "id": "MPL-2025-1009",
        "title": "Construction of Skill Training Centre & Workshop, Patancheru, Sangareddy",
        "hindiTitle": "कौशल प्रशिक्षण केंद्र एवं कार्यशाला, पाटनचेरु",
        "category": "Social Infrastructure",
        "state": STATE_NAME,
        "district": "Sangareddy",
        "constituency": "Medak",
        "mpName": "Shri Harish Chandran (Demo Constituency)",
        "dmName": "DM Nair (Demo)",
        "sanctionedAmountLakh": 38.0,
        "sanctionedDate": "10 Nov 2024",
        "status": "hold_active",
        "statusSince": "15 Aug 2025",
        "overview": "GHOST COMPLETION DETECTED: 90% (₹34.2L) of funds disbursed through 3 installments while ground physical progress remains at only 10% foundation level after 9 months.",
        "mpPlainStatus": "Held for physical vigilance audit: 90% funds drawn while only foundation pillars exist on ground.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 90, "peer_release_pct": 60, "peer_sd": 12},
            "payment": {
                "released_pct": 90,
                "completion_pct": 10,
                "months_since_sanction": 9,
            },
            "predictive": {
                "factors": ["Severe payment vs progress divergence", "No contractor milestone submission in 120 days"],
            },
            "compliance": {
                "checks": [
                    {"field": "MB Record verification", "actual": "MB un-certified for Stage 3", "required": "Certified Measurement Book", "rule_ref": "OP 2025–26 §6.2", "clause_text": "Disbursements strictly tied to Assistant Engineer MB certification.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Government ITI Campus", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 10. PFMS Redirection Alert Case (Medchal-Malkajgiri)
    {
        "id": "MPL-2025-1010",
        "title": "Establishment of RO Drinking Water Plant (1000 LPH), Ghatkesar, Medchal",
        "hindiTitle": "आरओ पेयजल संयंत्र की स्थापना (1000 LPH), घटकेसर",
        "category": "Drinking Water",
        "state": STATE_NAME,
        "district": "Medchal-Malkajgiri",
        "constituency": "Malkajgiri",
        "mpName": "Shri Vikram Rathore (Demo Constituency)",
        "dmName": "DM Iyer (Demo)",
        "sanctionedAmountLakh": 11.5,
        "sanctionedDate": "08 Feb 2025",
        "status": "hold_active",
        "statusSince": "14 Apr 2025",
        "overview": "PFMS INTEGRITY ALERT: Stage-2 fund release was requested to an un-bound bank account differing from the dedicated Stage-1 Implementing Agency account.",
        "mpPlainStatus": "Held for vendor reconciliation: Stage 2 payment account changed without logged administrative approval.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 45, "peer_release_pct": 62, "peer_sd": 10},
            "payment": {"released_pct": 40, "completion_pct": 40, "months_since_sanction": 5},
            "pfms": {
                "stage_number": 2,
                "stage1_account": "SBIN00014239871",
                "target_account": "HDFC00098471204",
                "vendor_gstin": "36AAAGW2345Q1Z6",
                "vendor_name": "Rural Water Supply & Sanitation Department",
            },
            "predictive": {"factors": []},
            "compliance": {
                "checks": [
                    {"field": "PFMS Account Binding", "actual": "Mismatched destination account", "required": "Consistent Stage 1 SNA Account", "rule_ref": "PFMS-SNA §3.4", "clause_text": "All project milestones must disburse into registered SNA single-nodal account.", "critical": False, "passed": False},
                    {"field": "Land ownership", "actual": "Gram Panchayat revenue land", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True},
                ]
            },
        },
    },
    # 11. Clean Case: Solar High Mast Array (Rangareddy)
    {
        "id": "MPL-2025-1011",
        "title": "Solar LED Street Light Installation across 8 Gram Panchayats, Shamshabad, Rangareddy",
        "hindiTitle": "8 ग्राम पंचायतों में सोलर एलईडी स्ट्रीट लाइट स्थापना, शमशाबाद",
        "category": "Renewable Energy",
        "state": STATE_NAME,
        "district": "Rangareddy",
        "constituency": "Chevella",
        "mpName": "Shri Konda Vishweshwar Reddy",
        "dmName": "DM Verma (Demo)",
        "sanctionedAmountLakh": 18.0,
        "sanctionedDate": "20 Jan 2025",
        "status": "released",
        "statusSince": "15 May 2025",
        "overview": "Solar illumination project executed by TSREDCO. All 80 fixtures commissioned, geotagged, and verified clean.",
        "mpPlainStatus": "Project 100% completed and handed over to local panchayats.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 100, "peer_release_pct": 82, "peer_sd": 8},
            "payment": {"released_pct": 100, "completion_pct": 100, "months_since_sanction": 6},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Public street right of way", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 12. Clean Case: High School STEM Laboratory (Hyderabad)
    {
        "id": "MPL-2025-1012",
        "title": "Modern Science & Robotics Lab, Govt High School, Khairatabad, Hyderabad",
        "hindiTitle": "आधुनिक विज्ञान एवं रोबोटिक्स लैब, सरकारी उच्च विद्यालय, खैरताबाद",
        "category": "Education",
        "state": STATE_NAME,
        "district": "Hyderabad",
        "constituency": "Secunderabad",
        "mpName": "Shri G. Kishan Reddy",
        "dmName": "DM Sharma (Demo)",
        "sanctionedAmountLakh": 22.0,
        "sanctionedDate": "14 Feb 2025",
        "status": "released",
        "statusSince": "28 Jun 2025",
        "overview": "State-of-the-art STEM equipment, smart boards, and laboratory benches supplied and installed under Education Department supervision.",
        "mpPlainStatus": "Completed and in active use by 650 students.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 95, "peer_release_pct": 80, "peer_sd": 8},
            "payment": {"released_pct": 100, "completion_pct": 100, "months_since_sanction": 5},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Government School Building", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 13. Clean Case: Primary Health Centre Ambulance Bay (Mahbubnagar)
    {
        "id": "MPL-2025-1013",
        "title": "Emergency Ambulance Shed & Triage Extension, CHC Bhoothpur, Mahbubnagar",
        "hindiTitle": "आपातकालीन एम्बुलेंस शेड एवं ट्राइएज विस्तार, सामुदायिक स्वास्थ्य केंद्र",
        "category": "Health & Sanitation",
        "state": STATE_NAME,
        "district": "Mahbubnagar",
        "constituency": "Mahbubnagar",
        "mpName": "Smt. D. K. Aruna",
        "dmName": "DM Rao (Demo)",
        "sanctionedAmountLakh": 14.2,
        "sanctionedDate": "18 Mar 2025",
        "status": "released",
        "statusSince": "05 Jul 2025",
        "overview": "Civil structural expansion of primary health triage bay completed within technical budget estimates.",
        "mpPlainStatus": "Civil works completed on schedule. Operational.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 85, "peer_release_pct": 75, "peer_sd": 10},
            "payment": {"released_pct": 80, "completion_pct": 85, "months_since_sanction": 5},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Govt Hospital Land", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 14. Evaluating Case: Anganwadi Centre Building (Rangareddy)
    {
        "id": "MPL-2025-1014",
        "title": "Construction of Model Anganwadi Centre, Ibrahimpatnam, Rangareddy",
        "hindiTitle": "मॉडल आंगनवाड़ी केंद्र का निर्माण, इब्राहिमपटनम",
        "category": "Social Infrastructure",
        "state": STATE_NAME,
        "district": "Rangareddy",
        "constituency": "Chevella",
        "mpName": "Shri Konda Vishweshwar Reddy",
        "dmName": "DM Verma (Demo)",
        "sanctionedAmountLakh": 13.5,
        "sanctionedDate": "01 Aug 2025",
        "status": "evaluating",
        "statusSince": "01 Aug 2025",
        "overview": "New proposal submitted by Women & Child Welfare dept; automated guardrail and cost baseline checks currently running clean.",
        "mpPlainStatus": "Under normal administrative clearance and technical evaluation.",
        "path": ["submitted", "evaluating"],
        "facts": {
            "trend": {"case_release_pct": 10, "peer_release_pct": 20, "peer_sd": 8},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 1},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Govt Revenue Patta", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 15. Evaluating Case: Drinking Water Pipe Network (Sangareddy)
    {
        "id": "MPL-2025-1015",
        "title": "Drinking Water Pipeline Network Extension, Sadasivpet, Sangareddy",
        "hindiTitle": "पेयजल पाइपलाइन नेटवर्क विस्तार, सदाशिवपेट",
        "category": "Drinking Water",
        "state": STATE_NAME,
        "district": "Sangareddy",
        "constituency": "Zaheerabad",
        "mpName": "Shri Suresh Kumar Shetkar",
        "dmName": "DM Nair (Demo)",
        "sanctionedAmountLakh": 21.0,
        "sanctionedDate": "22 Jul 2025",
        "status": "evaluating",
        "statusSince": "22 Jul 2025",
        "overview": "Pipeline interconnection project with Mission Bhagiratha grid. Technical sanction and BOQ verified aligned with schedule.",
        "mpPlainStatus": "Under administrative verification with Mission Bhagiratha engineers.",
        "path": ["submitted", "evaluating"],
        "facts": {
            "trend": {"case_release_pct": 15, "peer_release_pct": 25, "peer_sd": 8},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 1},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Municipal Road Right of Way", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 16. Clean Case: Community Crematorium Shed & Solar Lighting (Mahbubnagar)
    {
        "id": "MPL-2025-1016",
        "title": "Vaikunta Dhamam Crematorium Shed & High-Mast Solar Light, Devarakadra, Mahbubnagar",
        "hindiTitle": "वैकुंठ धाम शवदाह गृह शेड एवं सोलर लाइट, देवरकद्र",
        "category": "Community Assets",
        "state": STATE_NAME,
        "district": "Mahbubnagar",
        "constituency": "Mahbubnagar",
        "mpName": "Smt. D. K. Aruna",
        "dmName": "DM Rao (Demo)",
        "sanctionedAmountLakh": 17.5,
        "sanctionedDate": "10 Mar 2025",
        "status": "released",
        "statusSince": "25 May 2025",
        "overview": "Model rural crematorium facility completed with concrete shed, solar lighting, and dedicated water tank.",
        "mpPlainStatus": "Civil work 100% completed and handed over.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 90, "peer_release_pct": 80, "peer_sd": 10},
            "payment": {"released_pct": 90, "completion_pct": 95, "months_since_sanction": 5},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Gram Panchayat Allotted Land", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 17. Clean Case: Additional Classrooms in ZP High School (Medchal-Malkajgiri)
    {
        "id": "MPL-2025-1017",
        "title": "Construction of 2 Additional Classrooms, ZP High School, Alwal, Medchal",
        "hindiTitle": "2 अतिरिक्त कक्षाओं का निर्माण, जिला परिषद हाई स्कूल, अलवाल",
        "category": "Education",
        "state": STATE_NAME,
        "district": "Medchal-Malkajgiri",
        "constituency": "Malkajgiri",
        "mpName": "Shri Eatala Rajender",
        "dmName": "DM Iyer (Demo)",
        "sanctionedAmountLakh": 19.8,
        "sanctionedDate": "05 Jan 2025",
        "status": "released",
        "statusSince": "15 Apr 2025",
        "overview": "Two classroom block completed with dual desk benches, ceiling fans, and LED fixtures.",
        "mpPlainStatus": "Classrooms completed and operational for academic session.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 100, "peer_release_pct": 85, "peer_sd": 8},
            "payment": {"released_pct": 100, "completion_pct": 100, "months_since_sanction": 7},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "School Compound", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 18. Clean Case: CC Drain Construction (Hyderabad)
    {
        "id": "MPL-2025-1018",
        "title": "Construction of RCC Underground Storm Drain, Musheerabad, Hyderabad",
        "hindiTitle": "आरसीसी भूमिगत वर्षा जल नाली निर्माण, मुशीराबाद",
        "category": "Rural Roads",
        "state": STATE_NAME,
        "district": "Hyderabad",
        "constituency": "Hyderabad",
        "mpName": "Shri Asaduddin Owaisi",
        "dmName": "DM Sharma (Demo)",
        "sanctionedAmountLakh": 27.5,
        "sanctionedDate": "12 Feb 2025",
        "status": "released",
        "statusSince": "18 May 2025",
        "overview": "GHMC drainage expansion preventing seasonal waterlogging at Musheerabad junction.",
        "mpPlainStatus": "Completed ahead of monsoon schedule.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 90, "peer_release_pct": 82, "peer_sd": 8},
            "payment": {"released_pct": 85, "completion_pct": 90, "months_since_sanction": 6},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "GHMC Road Corridor", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 19. Evaluating Case: Women SHG Skill Centre (Sangareddy)
    {
        "id": "MPL-2025-1019",
        "title": "Establishment of Mahila Samakhya Livelihood Training Centre, Narayankhed, Sangareddy",
        "hindiTitle": "महिला समाख्या आजीविका प्रशिक्षण केंद्र, नारायणखेड़",
        "category": "Social Infrastructure",
        "state": STATE_NAME,
        "district": "Sangareddy",
        "constituency": "Medak",
        "mpName": "Shri M. Raghunandan Rao",
        "dmName": "DM Nair (Demo)",
        "sanctionedAmountLakh": 15.0,
        "sanctionedDate": "18 Aug 2025",
        "status": "evaluating",
        "statusSince": "18 Aug 2025",
        "overview": "Proposal for sewing, handicrafts, and digital literacy training unit for rural self-help groups.",
        "mpPlainStatus": "Under administrative review by DRDA / District Collectorate.",
        "path": ["submitted", "evaluating"],
        "facts": {
            "trend": {"case_release_pct": 5, "peer_release_pct": 15, "peer_sd": 6},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 1},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "DRDA Community Hall", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 20. Clean Case: RO Drinking Water Kiosk (Rangareddy)
    {
        "id": "MPL-2025-1020",
        "title": "Community RO Drinking Water Kiosk (500 LPH), Maheshwaram, Rangareddy",
        "hindiTitle": "सामुदायिक आरओ पेयजल कियोस्क (500 LPH), महेश्वरम",
        "category": "Drinking Water",
        "state": STATE_NAME,
        "district": "Rangareddy",
        "constituency": "Chevella",
        "mpName": "Shri Konda Vishweshwar Reddy",
        "dmName": "DM Verma (Demo)",
        "sanctionedAmountLakh": 8.5,
        "sanctionedDate": "04 Mar 2025",
        "status": "released",
        "statusSince": "22 Jun 2025",
        "overview": "Purified safe drinking water facility providing 20L cans to 400 rural households daily.",
        "mpPlainStatus": "Fully commissioned and serving drinking water to village community.",
        "path": ["submitted", "evaluating", "released"],
        "facts": {
            "trend": {"case_release_pct": 100, "peer_release_pct": 88, "peer_sd": 6},
            "payment": {"released_pct": 100, "completion_pct": 100, "months_since_sanction": 5},
            "predictive": {"factors": []},
            "compliance": {"checks": [{"field": "Land ownership", "actual": "Gram Panchayat Office Compound", "required": "Public", "rule_ref": "OP §4.1.3", "clause_text": "Public land", "critical": True, "passed": True}]},
        },
    },
    # 21. Un-suspecting Gate-Fired Case (Rangareddy - low composite, land tenure gate fired)
    {
        "id": "MPL-2025-1021",
        "title": "Community Meeting Shed & Drinking Water Shelter, Sy. No. 298, Shamshabad, Rangareddy",
        "hindiTitle": "सामुदायिक बैठक शेड एवं पेयजल शेल्टर, सर्वे नं. 298, शमशाबाद",
        "category": "Community Assets",
        "state": STATE_NAME,
        "district": "Rangareddy",
        "constituency": "Chevella",
        "mpName": "Shri Anant Rao (Demo Constituency)",
        "dmName": "DM Verma (Demo)",
        "sanctionedAmountLakh": 14.0,
        "sanctionedDate": "07 Jul 2025",
        "status": "hold_active",
        "statusSince": "07 Jul 2025",
        "overview": "GATE FIRED ON AN OTHERWISE LOW-RISK CASE: the proposed site is a private gated society plot (Sy. No. 298/A), not public or municipal land, so the Critical-Risk Gate holds the work even though the composite risk score stays in the low-30s.",
        "mpPlainStatus": "HARD GATE HOLD: Land tenure is private/un-regularised. This is not a threshold alert — it can only be waived against the record as a Gate Override.",
        "path": ["submitted", "evaluating", "hold_active"],
        "facts": {
            "trend": {"case_release_pct": 40, "peer_release_pct": 40, "peer_sd": 10},
            "payment": {"released_pct": 0, "completion_pct": 0, "months_since_sanction": 0},
            "predictive": {"factors": []},
            "duplicate": {},
            "photo": {},
            "compliance": {
                "checks": [
                    {
                        "field": "Land ownership",
                        "actual": "Private gated society land (Sy. No. 298/A)",
                        "required": "Public / Municipal Land",
                        "rule_ref": "OP 2025–26 §4.1.3",
                        "clause_text": "MPLADS funds can only create assets on land belonging to Government or a local body; private/un-regularised plots are ineligible.",
                        "critical": True,
                        "passed": False,
                    },
                    {"field": "Entity type", "actual": "Panchayat Raj Engineering Division", "required": "Eligible Public Entity", "rule_ref": "OP 2025–26 §2.1", "clause_text": "Implementing agency must be an authorized public department.", "critical": True, "passed": True},
                    {"field": "Technical sanction", "actual": "Approved", "required": "Approved", "rule_ref": "OP 2025–26 §5.2", "clause_text": "Rates aligned with nodal agency schedule.", "critical": False, "passed": True},
                    {"field": "Site safety (police clearance)", "actual": "Enclave internal road", "required": "Approachable", "rule_ref": "OP 2025–26 §5.4", "clause_text": "Approach road available.", "critical": False, "passed": True},
                    {"field": "Asset durability", "actual": "RCC structure", "required": "Semi-permanent or better", "rule_ref": "OP 2025–26 §5.6", "clause_text": "Asset should be durable.", "critical": False, "passed": True},
                    {"field": "Recurring cost", "actual": "None", "required": "None or local body borne", "rule_ref": "OP 2025–26 §5.7", "clause_text": "No recurring burden on the state.", "critical": False, "passed": True},
                ]
            },
        },
    },
]

COST_BASELINES = [
    {"category": "Rural Roads", "district": "Hyderabad", "terrain": "plain", "median_lakh": 24.0, "mad_log_cost": 0.28, "low_lakh": 18.0, "high_lakh": 32.0, "n_records": 48},
    {"category": "Rural Roads", "district": "Rangareddy", "terrain": "plain", "median_lakh": 22.5, "mad_log_cost": 0.30, "low_lakh": 16.0, "high_lakh": 30.0, "n_records": 52},
    {"category": "Rural Roads", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 21.0, "mad_log_cost": 0.29, "low_lakh": 15.0, "high_lakh": 28.0, "n_records": 42},
    {"category": "Rural Roads", "district": "Sangareddy", "terrain": "semi-hilly", "median_lakh": 22.0, "mad_log_cost": 0.26, "low_lakh": 16.0, "high_lakh": 29.0, "n_records": 39},
    {"category": "Rural Roads", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 19.5, "mad_log_cost": 0.32, "low_lakh": 14.0, "high_lakh": 26.0, "n_records": 36},
    {"category": "Community Assets", "district": "Hyderabad", "terrain": "plain", "median_lakh": 18.0, "mad_log_cost": 0.35, "low_lakh": 12.0, "high_lakh": 26.0, "n_records": 60},
    {"category": "Community Assets", "district": "Rangareddy", "terrain": "plain", "median_lakh": 16.5, "mad_log_cost": 0.34, "low_lakh": 11.0, "high_lakh": 24.0, "n_records": 55},
    {"category": "Community Assets", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 15.0, "mad_log_cost": 0.32, "low_lakh": 10.0, "high_lakh": 22.0, "n_records": 47},
    {"category": "Community Assets", "district": "Sangareddy", "terrain": "plain", "median_lakh": 14.5, "mad_log_cost": 0.33, "low_lakh": 9.5, "high_lakh": 21.0, "n_records": 40},
    {"category": "Community Assets", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 13.5, "mad_log_cost": 0.36, "low_lakh": 8.5, "high_lakh": 20.0, "n_records": 38},
    {"category": "Drinking Water", "district": "Hyderabad", "terrain": "plain", "median_lakh": 12.0, "mad_log_cost": 0.25, "low_lakh": 8.0, "high_lakh": 16.0, "n_records": 35},
    {"category": "Drinking Water", "district": "Rangareddy", "terrain": "plain", "median_lakh": 10.5, "mad_log_cost": 0.28, "low_lakh": 7.0, "high_lakh": 15.0, "n_records": 44},
    {"category": "Drinking Water", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 10.0, "mad_log_cost": 0.27, "low_lakh": 6.5, "high_lakh": 14.5, "n_records": 38},
    {"category": "Drinking Water", "district": "Sangareddy", "terrain": "plain", "median_lakh": 11.0, "mad_log_cost": 0.26, "low_lakh": 7.5, "high_lakh": 15.5, "n_records": 41},
    {"category": "Drinking Water", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 9.5, "mad_log_cost": 0.30, "low_lakh": 6.0, "high_lakh": 14.0, "n_records": 45},
    {"category": "Renewable Energy", "district": "Hyderabad", "terrain": "plain", "median_lakh": 16.0, "mad_log_cost": 0.28, "low_lakh": 11.0, "high_lakh": 22.0, "n_records": 30},
    {"category": "Renewable Energy", "district": "Rangareddy", "terrain": "plain", "median_lakh": 15.0, "mad_log_cost": 0.29, "low_lakh": 10.0, "high_lakh": 21.0, "n_records": 34},
    {"category": "Renewable Energy", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 14.5, "mad_log_cost": 0.27, "low_lakh": 9.5, "high_lakh": 20.0, "n_records": 29},
    {"category": "Renewable Energy", "district": "Sangareddy", "terrain": "plain", "median_lakh": 14.0, "mad_log_cost": 0.30, "low_lakh": 9.0, "high_lakh": 19.5, "n_records": 32},
    {"category": "Renewable Energy", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 14.0, "mad_log_cost": 0.29, "low_lakh": 9.0, "high_lakh": 19.0, "n_records": 31},
    {"category": "Education", "district": "Hyderabad", "terrain": "plain", "median_lakh": 20.0, "mad_log_cost": 0.27, "low_lakh": 14.0, "high_lakh": 27.0, "n_records": 45},
    {"category": "Education", "district": "Rangareddy", "terrain": "plain", "median_lakh": 18.0, "mad_log_cost": 0.28, "low_lakh": 12.0, "high_lakh": 25.0, "n_records": 40},
    {"category": "Education", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 17.5, "mad_log_cost": 0.26, "low_lakh": 12.0, "high_lakh": 24.0, "n_records": 36},
    {"category": "Education", "district": "Sangareddy", "terrain": "plain", "median_lakh": 16.0, "mad_log_cost": 0.29, "low_lakh": 11.0, "high_lakh": 22.0, "n_records": 33},
    {"category": "Education", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 15.0, "mad_log_cost": 0.31, "low_lakh": 10.0, "high_lakh": 21.0, "n_records": 35},
    {"category": "Health & Sanitation", "district": "Hyderabad", "terrain": "plain", "median_lakh": 21.0, "mad_log_cost": 0.26, "low_lakh": 15.0, "high_lakh": 28.0, "n_records": 42},
    {"category": "Health & Sanitation", "district": "Rangareddy", "terrain": "plain", "median_lakh": 18.5, "mad_log_cost": 0.28, "low_lakh": 13.0, "high_lakh": 25.0, "n_records": 39},
    {"category": "Health & Sanitation", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 17.5, "mad_log_cost": 0.27, "low_lakh": 12.0, "high_lakh": 24.0, "n_records": 34},
    {"category": "Health & Sanitation", "district": "Sangareddy", "terrain": "plain", "median_lakh": 16.5, "mad_log_cost": 0.29, "low_lakh": 11.0, "high_lakh": 23.0, "n_records": 30},
    {"category": "Health & Sanitation", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 15.5, "mad_log_cost": 0.30, "low_lakh": 10.5, "high_lakh": 21.5, "n_records": 32},
    {"category": "Social Infrastructure", "district": "Hyderabad", "terrain": "plain", "median_lakh": 16.0, "mad_log_cost": 0.30, "low_lakh": 11.0, "high_lakh": 22.0, "n_records": 40},
    {"category": "Social Infrastructure", "district": "Rangareddy", "terrain": "plain", "median_lakh": 14.5, "mad_log_cost": 0.32, "low_lakh": 9.5, "high_lakh": 20.5, "n_records": 44},
    {"category": "Social Infrastructure", "district": "Medchal-Malkajgiri", "terrain": "plain", "median_lakh": 14.0, "mad_log_cost": 0.31, "low_lakh": 9.0, "high_lakh": 19.5, "n_records": 37},
    {"category": "Social Infrastructure", "district": "Sangareddy", "terrain": "plain", "median_lakh": 13.5, "mad_log_cost": 0.33, "low_lakh": 8.5, "high_lakh": 19.0, "n_records": 35},
    {"category": "Social Infrastructure", "district": "Mahbubnagar", "terrain": "plain", "median_lakh": 12.5, "mad_log_cost": 0.35, "low_lakh": 8.0, "high_lakh": 18.0, "n_records": 38},
]

DISTRICT_QUARTERLY = [
    {"district": "Hyderabad", "q1": 88, "q2": 92, "q3": 85, "q4": 90, "ytd": 89},
    {"district": "Rangareddy", "q1": 78, "q2": 84, "q3": 80, "q4": 86, "ytd": 82},
    {"district": "Medchal-Malkajgiri", "q1": 82, "q2": 80, "q3": 76, "q4": 85, "ytd": 81},
    {"district": "Sangareddy", "q1": 65, "q2": 70, "q3": 62, "q4": 74, "ytd": 68},
    {"district": "Mahbubnagar", "q1": 70, "q2": 72, "q3": 68, "q4": 76, "ytd": 72},
]

MONTHLY_TREND = [
    {"month": "Apr", "district": "Hyderabad", "release_pct": 18},
    {"month": "May", "district": "Hyderabad", "release_pct": 36},
    {"month": "Jun", "district": "Hyderabad", "release_pct": 54},
    {"month": "Jul", "district": "Hyderabad", "release_pct": 72},
    {"month": "Aug", "district": "Hyderabad", "release_pct": 89},
    {"month": "Apr", "district": "Rangareddy", "release_pct": 15},
    {"month": "May", "district": "Rangareddy", "release_pct": 32},
    {"month": "Jun", "district": "Rangareddy", "release_pct": 48},
    {"month": "Jul", "district": "Rangareddy", "release_pct": 65},
    {"month": "Aug", "district": "Rangareddy", "release_pct": 82},
    {"month": "Apr", "district": "Medchal-Malkajgiri", "release_pct": 16},
    {"month": "May", "district": "Medchal-Malkajgiri", "release_pct": 30},
    {"month": "Jun", "district": "Medchal-Malkajgiri", "release_pct": 49},
    {"month": "Jul", "district": "Medchal-Malkajgiri", "release_pct": 66},
    {"month": "Aug", "district": "Medchal-Malkajgiri", "release_pct": 81},
    {"month": "Apr", "district": "Sangareddy", "release_pct": 12},
    {"month": "May", "district": "Sangareddy", "release_pct": 24},
    {"month": "Jun", "district": "Sangareddy", "release_pct": 38},
    {"month": "Jul", "district": "Sangareddy", "release_pct": 52},
    {"month": "Aug", "district": "Sangareddy", "release_pct": 68},
    {"month": "Apr", "district": "Mahbubnagar", "release_pct": 14},
    {"month": "May", "district": "Mahbubnagar", "release_pct": 26},
    {"month": "Jun", "district": "Mahbubnagar", "release_pct": 42},
    {"month": "Jul", "district": "Mahbubnagar", "release_pct": 58},
    {"month": "Aug", "district": "Mahbubnagar", "release_pct": 72},
]

STATE_STATS = [
    {"state": "Telangana", "utilization": 84, "cases": 20},
    {"state": "Andhra Pradesh", "utilization": 81, "cases": 18},
    {"state": "Karnataka", "utilization": 86, "cases": 24},
    {"state": "Maharashtra", "utilization": 79, "cases": 28},
    {"state": "Tamil Nadu", "utilization": 88, "cases": 26},
]

CATEGORY_STATS = [
    {"category": "Rural Roads", "sanctions_cr": 14.8, "releases_cr": 12.1},
    {"category": "Community Assets", "sanctions_cr": 11.2, "releases_cr": 9.4},
    {"category": "Drinking Water", "sanctions_cr": 8.6, "releases_cr": 7.3},
    {"category": "Education", "sanctions_cr": 9.4, "releases_cr": 8.0},
    {"category": "Health & Sanitation", "sanctions_cr": 7.8, "releases_cr": 6.5},
    {"category": "Renewable Energy", "sanctions_cr": 6.2, "releases_cr": 5.4},
    {"category": "Social Infrastructure", "sanctions_cr": 5.5, "releases_cr": 4.6},
]

MP_STATS = [
    {
        "mp_name": "Shri G. Kishan Reddy",
        "used_cr": 4.82,
        "breakdown": {"Education": 1.45, "Community Assets": 1.62, "Health & Sanitation": 0.95, "Rural Roads": 0.80},
    },
    {
        "mp_name": "Shri Eatala Rajender",
        "used_cr": 4.45,
        "breakdown": {"Rural Roads": 1.85, "Drinking Water": 0.95, "Education": 1.15, "Community Assets": 0.50},
    },
    {
        "mp_name": "Shri Konda Vishweshwar Reddy",
        "used_cr": 4.60,
        "breakdown": {"Renewable Energy": 1.20, "Drinking Water": 0.90, "Community Assets": 1.50, "Social Infrastructure": 1.00},
    },
    {
        "mp_name": "Shri Suresh Kumar Shetkar",
        "used_cr": 3.90,
        "breakdown": {"Rural Roads": 2.10, "Drinking Water": 0.95, "Social Infrastructure": 0.85},
    },
    {
        "mp_name": "Smt. D. K. Aruna",
        "used_cr": 4.15,
        "breakdown": {"Health & Sanitation": 1.35, "Renewable Energy": 1.10, "Community Assets": 1.20, "Rural Roads": 0.50},
    },
    {
        "mp_name": "Shri Asaduddin Owaisi",
        "used_cr": 4.70,
        "breakdown": {"Health & Sanitation": 1.95, "Education": 1.50, "Community Assets": 1.25},
    },
    {
        "mp_name": "Shri M. Raghunandan Rao",
        "used_cr": 3.80,
        "breakdown": {"Social Infrastructure": 1.60, "Rural Roads": 1.40, "Drinking Water": 0.80},
    },
]

OFFICIALS = [
    {
        "name": "DM Sharma (Demo)",
        "role": "District Collector & Magistrate",
        "district": "Hyderabad",
        "high_risk_decisions": 4,
        "gate_overrides": 0,
        "threshold_overrides": 1,
        "flagged_note": "Rigorous adherence to compliance gate protocols.",
    },
    {
        "name": "DM Verma (Demo)",
        "role": "District Collector & Magistrate",
        "district": "Rangareddy",
        "high_risk_decisions": 5,
        "gate_overrides": 0,
        "threshold_overrides": 2,
        "flagged_note": "Active monitoring on land regularisation checks.",
    },
    {
        "name": "DM Iyer (Demo)",
        "role": "District Collector & Magistrate",
        "district": "Medchal-Malkajgiri",
        "high_risk_decisions": 6,
        "gate_overrides": 1,
        "threshold_overrides": 2,
        "flagged_note": "1 Gate override under scrutiny for vendor binding.",
    },
    {
        "name": "DM Nair (Demo)",
        "role": "District Collector & Magistrate",
        "district": "Sangareddy",
        "high_risk_decisions": 7,
        "gate_overrides": 0,
        "threshold_overrides": 3,
        "flagged_note": "Elevated threshold override rate on road infrastructure.",
    },
    {
        "name": "DM Rao (Demo)",
        "role": "District Collector & Magistrate",
        "district": "Mahbubnagar",
        "high_risk_decisions": 3,
        "gate_overrides": 0,
        "threshold_overrides": 1,
        "flagged_note": "Cost variance holds strictly enforced.",
    },
]

LEDGER_SEEDS = [
    {
        "action": "GENESIS BLOCK",
        "category": "system",
        "actor": "system",
        "actor_role": "Sentinel Genesis Authority",
        "body": "MPLADS Sentinel Cryptographic Audit Chain Initialized for Telangana State.",
        "timestamp": "2025-01-01T00:00:00",
        "case_id": None,
    },
    {
        "action": "PROPOSAL INGESTED",
        "category": "ingestion",
        "actor": "system",
        "actor_role": "Sentinel Ingestion Engine",
        "body": "eSAKSHI Work MPL-2025-1002 ingested & verified clean. Composite Risk: 14/100.",
        "timestamp": "2025-01-10T10:15:00",
        "case_id": "MPL-2025-1002",
    },
    {
        "action": "GATE HOLD FIRED",
        "category": "hold",
        "actor": "system",
        "actor_role": "Sentinel Circuit Breaker Gate",
        "body": "Hard Gate M9 triggered on MPL-2025-1007: Private land tenure detected.",
        "timestamp": "2025-06-05T14:30:00",
        "case_id": "MPL-2025-1007",
    },
    {
        "action": "PHOTO GATE FIRED",
        "category": "hold",
        "actor": "system",
        "actor_role": "Sentinel Circuit Breaker Gate",
        "body": "Hard Gate M9 triggered on MPL-2025-1008: Stage photo pHash match 99.6% vs prior work.",
        "timestamp": "2025-05-25T11:45:00",
        "case_id": "MPL-2025-1008",
    },
    {
        "action": "ESCALATED TO AUDIT",
        "category": "escalate",
        "actor": "dm_sangareddy",
        "actor_role": "District Magistrate, Sangareddy",
        "body": "Escalated MPL-2025-1005 to State Engineering Auditor for BOQ inflation review.",
        "timestamp": "2025-06-22T16:00:00",
        "case_id": "MPL-2025-1005",
    },
]

OVERRIDES = [
    {
        "case_id": "MPL-2025-1003",
        "kind": "threshold",
        "official_name": "DM Iyer (Demo)",
        "official_district": "Medchal-Malkajgiri",
        "action": "HELD FOR INSPECTION",
        "body": "Inspection ordered for duplicate overlap at Pragathi Nagar with Municipal AE.",
        "timestamp": "2025-08-18T15:20:00",
        "ledger_index": 5,
    }
]